//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Presentacion.Recursos.Base {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenericoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericoResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Presentacion.Recursos.Base.GenericoResource", typeof(GenericoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string BotonAceptar {
            get {
                return ResourceManager.GetString("BotonAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string BotonAgregar {
            get {
                return ResourceManager.GetString("BotonAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string BotonAñadir {
            get {
                return ResourceManager.GetString("BotonAñadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string BotonAnterior {
            get {
                return ResourceManager.GetString("BotonAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplica.
        /// </summary>
        public static string BotonAplica {
            get {
                return ResourceManager.GetString("BotonAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string BotonAprobar {
            get {
                return ResourceManager.GetString("BotonAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizar.
        /// </summary>
        public static string BotonAutorizar {
            get {
                return ResourceManager.GetString("BotonAutorizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string BotonBuscar {
            get {
                return ResourceManager.GetString("BotonBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string BotonCancelar {
            get {
                return ResourceManager.GetString("BotonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string BotonCerrar {
            get {
                return ResourceManager.GetString("BotonCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string BotonCerrarSesion {
            get {
                return ResourceManager.GetString("BotonCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        public static string BotonCopiar {
            get {
                return ResourceManager.GetString("BotonCopiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denegar.
        /// </summary>
        public static string BotonDenegar {
            get {
                return ResourceManager.GetString("BotonDenegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string BotonEliminar {
            get {
                return ResourceManager.GetString("BotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string BotonEnviar {
            get {
                return ResourceManager.GetString("BotonEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        public static string BotonExportar {
            get {
                return ResourceManager.GetString("BotonExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar Contrato.
        /// </summary>
        public static string BotonFinalizarContrato {
            get {
                return ResourceManager.GetString("BotonFinalizarContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabar.
        /// </summary>
        public static string BotonGrabar {
            get {
                return ResourceManager.GetString("BotonGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string BotonLimpiar {
            get {
                return ResourceManager.GetString("BotonLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar.
        /// </summary>
        public static string BotonMostrar {
            get {
                return ResourceManager.GetString("BotonMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Aplica.
        /// </summary>
        public static string BotonNoAplica {
            get {
                return ResourceManager.GetString("BotonNoAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string BotonRechazar {
            get {
                return ResourceManager.GetString("BotonRechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responder.
        /// </summary>
        public static string BotonResponder {
            get {
                return ResourceManager.GetString("BotonResponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string BotonSeleccionar {
            get {
                return ResourceManager.GetString("BotonSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string BotonSiguiente {
            get {
                return ResourceManager.GetString("BotonSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista Previa.
        /// </summary>
        public static string BotonVistaPrevia {
            get {
                return ResourceManager.GetString("BotonVistaPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string BtnRegresar {
            get {
                return ResourceManager.GetString("BtnRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTIVA.
        /// </summary>
        public static string EtiquetaActiva {
            get {
                return ResourceManager.GetString("EtiquetaActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar Plantilla.
        /// </summary>
        public static string EtiquetaCopiarPlantilla {
            get {
                return ResourceManager.GetString("EtiquetaCopiarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electronico.
        /// </summary>
        public static string EtiquetaCorreoElectronico {
            get {
                return ResourceManager.GetString("EtiquetaCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        public static string EtiquetaDesde {
            get {
                return ResourceManager.GetString("EtiquetaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EtiquetaEditar {
            get {
                return ResourceManager.GetString("EtiquetaEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar contrato.
        /// </summary>
        public static string EtiquetaEditarContenidoContrato {
            get {
                return ResourceManager.GetString("EtiquetaEditarContenidoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string EtiquetaEliminar {
            get {
                return ResourceManager.GetString("EtiquetaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string EtiquetaFecha {
            get {
                return ResourceManager.GetString("EtiquetaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *** FIN DE {0} ***.
        /// </summary>
        public static string EtiquetaFinReporte {
            get {
                return ResourceManager.GetString("EtiquetaFinReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar Archivo.
        /// </summary>
        public static string EtiquetaGridFileUpload {
            get {
                return ResourceManager.GetString("EtiquetaGridFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        public static string EtiquetaHasta {
            get {
                return ResourceManager.GetString("EtiquetaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        public static string EtiquetaImagen {
            get {
                return ResourceManager.GetString("EtiquetaImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INACTIVA.
        /// </summary>
        public static string EtiquetaInactiva {
            get {
                return ResourceManager.GetString("EtiquetaInactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO.
        /// </summary>
        public static string EtiquetaNo {
            get {
                return ResourceManager.GetString("EtiquetaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        public static string EtiquetaNotificaciones {
            get {
                return ResourceManager.GetString("EtiquetaNotificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificar.
        /// </summary>
        public static string EtiquetaNotificar {
            get {
                return ResourceManager.GetString("EtiquetaNotificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        public static string EtiquetaNumero {
            get {
                return ResourceManager.GetString("EtiquetaNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Contrato.
        /// </summary>
        public static string EtiquetaNumeroContrato {
            get {
                return ResourceManager.GetString("EtiquetaNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar.
        /// </summary>
        public static string EtiquetaReenviar {
            get {
                return ResourceManager.GetString("EtiquetaReenviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responder.
        /// </summary>
        public static string EtiquetaResponder {
            get {
                return ResourceManager.GetString("EtiquetaResponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados de Búsqueda.
        /// </summary>
        public static string EtiquetaResultadosBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (SELECCIONAR).
        /// </summary>
        public static string EtiquetaSeleccionar {
            get {
                return ResourceManager.GetString("EtiquetaSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SI.
        /// </summary>
        public static string EtiquetaSi {
            get {
                return ResourceManager.GetString("EtiquetaSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla.
        /// </summary>
        public static string EtiquetaTabla {
            get {
                return ResourceManager.GetString("EtiquetaTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        public static string EtiquetaTexto {
            get {
                return ResourceManager.GetString("EtiquetaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string EtiquetaTituloConfirmar {
            get {
                return ResourceManager.GetString("EtiquetaTituloConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (TODOS).
        /// </summary>
        public static string EtiquetaTodos {
            get {
                return ResourceManager.GetString("EtiquetaTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string EtiquetaUnidadOperativa {
            get {
                return ResourceManager.GetString("EtiquetaUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vencido.
        /// </summary>
        public static string EtiquetaVencido {
            get {
                return ResourceManager.GetString("EtiquetaVencido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar :.
        /// </summary>
        public static string EtiquetaVerificar {
            get {
                return ResourceManager.GetString("EtiquetaVerificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente.
        /// </summary>
        public static string EtiquetaVigente {
            get {
                return ResourceManager.GetString("EtiquetaVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizar.
        /// </summary>
        public static string EtiquetaVisualizar {
            get {
                return ResourceManager.GetString("EtiquetaVisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string GridAcciones {
            get {
                return ResourceManager.GetString("GridAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntos.
        /// </summary>
        public static string GridAdjunto {
            get {
                return ResourceManager.GetString("GridAdjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AgregarVariable.
        /// </summary>
        public static string GridAgregarVariable {
            get {
                return ResourceManager.GetString("GridAgregarVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string GridAprobar {
            get {
                return ResourceManager.GetString("GridAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar.
        /// </summary>
        public static string GridConsulta {
            get {
                return ResourceManager.GetString("GridConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        public static string GridContrato {
            get {
                return ResourceManager.GetString("GridContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controles.
        /// </summary>
        public static string GridControles {
            get {
                return ResourceManager.GetString("GridControles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        public static string GridCopiar {
            get {
                return ResourceManager.GetString("GridCopiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar Estadios.
        /// </summary>
        public static string GridCopiarEstadio {
            get {
                return ResourceManager.GetString("GridCopiarEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string GridDescargar {
            get {
                return ResourceManager.GetString("GridDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        public static string GridDetalle {
            get {
                return ResourceManager.GetString("GridDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadios.
        /// </summary>
        public static string GridEstadios {
            get {
                return ResourceManager.GetString("GridEstadios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observar.
        /// </summary>
        public static string GridObservacion {
            get {
                return ResourceManager.GetString("GridObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Párrafos.
        /// </summary>
        public static string GridParrafo {
            get {
                return ResourceManager.GetString("GridParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PDF.
        /// </summary>
        public static string GridPdf {
            get {
                return ResourceManager.GetString("GridPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Predecesora.
        /// </summary>
        public static string GridPredecesora {
            get {
                return ResourceManager.GetString("GridPredecesora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Alquiler.
        /// </summary>
        public static string GridValorAlquiler {
            get {
                return ResourceManager.GetString("GridValorAlquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista Previa.
        /// </summary>
        public static string GridVistaPrevia {
            get {
                return ResourceManager.GetString("GridVistaPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SISTEMA DE GESTIÓN CONTRACTUAL.
        /// </summary>
        public static string NombreSistema {
            get {
                return ResourceManager.GetString("NombreSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntos.
        /// </summary>
        public static string TituloAdjuntos {
            get {
                return ResourceManager.GetString("TituloAdjuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar al menos un valor.
        /// </summary>
        public static string ValidacionAlmenosUno {
            get {
                return ResourceManager.GetString("ValidacionAlmenosUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningún Campo puede tener números negativos.
        /// </summary>
        public static string ValidacionNumeroNegativo {
            get {
                return ResourceManager.GetString("ValidacionNumeroNegativo", resourceCulture);
            }
        }
    }
}
