//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Reportes.Recursos.Comun {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralStracon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralStracon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Reportes.Recursos.Comun.GeneralStracon", typeof(GeneralStracon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Estadio.
        /// </summary>
        public static string columnFechaEstadio {
            get {
                return ResourceManager.GetString("columnFechaEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Contrato.
        /// </summary>
        public static string columnNumeroContrato {
            get {
                return ResourceManager.GetString("columnNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Proveedor.
        /// </summary>
        public static string columnProveedor {
            get {
                return ResourceManager.GetString("columnProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUC Proveedor.
        /// </summary>
        public static string columnRucProveedor {
            get {
                return ResourceManager.GetString("columnRucProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Operativa.
        /// </summary>
        public static string columnUnidadOperativa {
            get {
                return ResourceManager.GetString("columnUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string txtAbril {
            get {
                return ResourceManager.GetString("txtAbril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string txtAgosto {
            get {
                return ResourceManager.GetString("txtAgosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área.
        /// </summary>
        public static string txtArea {
            get {
                return ResourceManager.GetString("txtArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diciembre.
        /// </summary>
        public static string txtDiciembre {
            get {
                return ResourceManager.GetString("txtDiciembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero.
        /// </summary>
        public static string txtEnero {
            get {
                return ResourceManager.GetString("txtEnero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febrero.
        /// </summary>
        public static string txtFebrero {
            get {
                return ResourceManager.GetString("txtFebrero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string txtFecha {
            get {
                return ResourceManager.GetString("txtFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de Edición.
        /// </summary>
        public static string txtFormaEdicion {
            get {
                return ResourceManager.GetString("txtFormaEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generados Desde.
        /// </summary>
        public static string txtGeneradosDesde {
            get {
                return ResourceManager.GetString("txtGeneradosDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generados Hasta.
        /// </summary>
        public static string txtGeneradosHasta {
            get {
                return ResourceManager.GetString("txtGeneradosHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SISTEMA DE GESTIÓN CONTRACTUAL.
        /// </summary>
        public static string txtGeneral {
            get {
                return ResourceManager.GetString("txtGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string txtHasta {
            get {
                return ResourceManager.GetString("txtHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string txtHora {
            get {
                return ResourceManager.GetString("txtHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio.
        /// </summary>
        public static string txtJulio {
            get {
                return ResourceManager.GetString("txtJulio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junio.
        /// </summary>
        public static string txtJunio {
            get {
                return ResourceManager.GetString("txtJunio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        public static string txtMarzo {
            get {
                return ResourceManager.GetString("txtMarzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayo.
        /// </summary>
        public static string txtMayo {
            get {
                return ResourceManager.GetString("txtMayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string txtNo {
            get {
                return ResourceManager.GetString("txtNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noviembre.
        /// </summary>
        public static string txtNoviembre {
            get {
                return ResourceManager.GetString("txtNoviembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Contrato.
        /// </summary>
        public static string txtNumeroContrato {
            get {
                return ResourceManager.GetString("txtNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octubre.
        /// </summary>
        public static string txtOctubre {
            get {
                return ResourceManager.GetString("txtOctubre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string txtPagina {
            get {
                return ResourceManager.GetString("txtPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string txtPaginaDe {
            get {
                return ResourceManager.GetString("txtPaginaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setiembre.
        /// </summary>
        public static string txtSetiembre {
            get {
                return ResourceManager.GetString("txtSetiembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (TODOS).
        /// </summary>
        public static string txtTodos {
            get {
                return ResourceManager.GetString("txtTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Operativa.
        /// </summary>
        public static string txtUnidadOperativa {
            get {
                return ResourceManager.GetString("txtUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string txtUsuario {
            get {
                return ResourceManager.GetString("txtUsuario", resourceCulture);
            }
        }
    }
}
