//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.GyM.Security.Account.SSOAuthenticateService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebUser", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class WebUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] B_PHOTO_USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S_DOMAIN_REDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S_EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S_FULL_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S_LAST_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S_LAST_NAME_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S_LAST_NAME_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S_LOGINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] B_PHOTO_USER {
            get {
                return this.B_PHOTO_USERField;
            }
            set {
                if ((object.ReferenceEquals(this.B_PHOTO_USERField, value) != true)) {
                    this.B_PHOTO_USERField = value;
                    this.RaisePropertyChanged("B_PHOTO_USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_USER {
            get {
                return this.ID_USERField;
            }
            set {
                if ((this.ID_USERField.Equals(value) != true)) {
                    this.ID_USERField = value;
                    this.RaisePropertyChanged("ID_USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S_DOMAIN_RED {
            get {
                return this.S_DOMAIN_REDField;
            }
            set {
                if ((object.ReferenceEquals(this.S_DOMAIN_REDField, value) != true)) {
                    this.S_DOMAIN_REDField = value;
                    this.RaisePropertyChanged("S_DOMAIN_RED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S_EMAIL {
            get {
                return this.S_EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.S_EMAILField, value) != true)) {
                    this.S_EMAILField = value;
                    this.RaisePropertyChanged("S_EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S_FULL_NAME {
            get {
                return this.S_FULL_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.S_FULL_NAMEField, value) != true)) {
                    this.S_FULL_NAMEField = value;
                    this.RaisePropertyChanged("S_FULL_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S_LAST_NAME {
            get {
                return this.S_LAST_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.S_LAST_NAMEField, value) != true)) {
                    this.S_LAST_NAMEField = value;
                    this.RaisePropertyChanged("S_LAST_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S_LAST_NAME_1 {
            get {
                return this.S_LAST_NAME_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.S_LAST_NAME_1Field, value) != true)) {
                    this.S_LAST_NAME_1Field = value;
                    this.RaisePropertyChanged("S_LAST_NAME_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S_LAST_NAME_2 {
            get {
                return this.S_LAST_NAME_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.S_LAST_NAME_2Field, value) != true)) {
                    this.S_LAST_NAME_2Field = value;
                    this.RaisePropertyChanged("S_LAST_NAME_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S_LOGIN {
            get {
                return this.S_LOGINField;
            }
            set {
                if ((object.ReferenceEquals(this.S_LOGINField, value) != true)) {
                    this.S_LOGINField = value;
                    this.RaisePropertyChanged("S_LOGIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S_NAME {
            get {
                return this.S_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.S_NAMEField, value) != true)) {
                    this.S_NAMEField = value;
                    this.RaisePropertyChanged("S_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserStatus", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UserStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequestIdValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UserLoggedInField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequestIdValid {
            get {
                return this.RequestIdValidField;
            }
            set {
                if ((this.RequestIdValidField.Equals(value) != true)) {
                    this.RequestIdValidField = value;
                    this.RaisePropertyChanged("RequestIdValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UserLoggedIn {
            get {
                return this.UserLoggedInField;
            }
            set {
                if ((this.UserLoggedInField.Equals(value) != true)) {
                    this.UserLoggedInField = value;
                    this.RaisePropertyChanged("UserLoggedIn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SSOAuthenticateService.IAuthenticateService")]
    public interface IAuthenticateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/Authenticate", ReplyAction="http://tempuri.org/IAuthenticateService/AuthenticateResponse")]
        Pe.GyM.Security.Account.SSOAuthenticateService.WebUser Authenticate(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/Authenticate", ReplyAction="http://tempuri.org/IAuthenticateService/AuthenticateResponse")]
        System.Threading.Tasks.Task<Pe.GyM.Security.Account.SSOAuthenticateService.WebUser> AuthenticateAsync(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/GetUserByToken", ReplyAction="http://tempuri.org/IAuthenticateService/GetUserByTokenResponse")]
        Pe.GyM.Security.Account.SSOAuthenticateService.WebUser GetUserByToken(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/GetUserByToken", ReplyAction="http://tempuri.org/IAuthenticateService/GetUserByTokenResponse")]
        System.Threading.Tasks.Task<Pe.GyM.Security.Account.SSOAuthenticateService.WebUser> GetUserByTokenAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/IsUserLoggedIn", ReplyAction="http://tempuri.org/IAuthenticateService/IsUserLoggedInResponse")]
        bool IsUserLoggedIn(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/IsUserLoggedIn", ReplyAction="http://tempuri.org/IAuthenticateService/IsUserLoggedInResponse")]
        System.Threading.Tasks.Task<bool> IsUserLoggedInAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/IsValidRequest", ReplyAction="http://tempuri.org/IAuthenticateService/IsValidRequestResponse")]
        bool IsValidRequest(string RedirectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/IsValidRequest", ReplyAction="http://tempuri.org/IAuthenticateService/IsValidRequestResponse")]
        System.Threading.Tasks.Task<bool> IsValidRequestAsync(string RedirectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/GetUserStauts", ReplyAction="http://tempuri.org/IAuthenticateService/GetUserStautsResponse")]
        Pe.GyM.Security.Account.SSOAuthenticateService.UserStatus GetUserStauts(string Token, string RequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/GetUserStauts", ReplyAction="http://tempuri.org/IAuthenticateService/GetUserStautsResponse")]
        System.Threading.Tasks.Task<Pe.GyM.Security.Account.SSOAuthenticateService.UserStatus> GetUserStautsAsync(string Token, string RequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/GetAccessToSystem", ReplyAction="http://tempuri.org/IAuthenticateService/GetAccessToSystemResponse")]
        bool GetAccessToSystem(string systemToken, System.Nullable<int> idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateService/GetAccessToSystem", ReplyAction="http://tempuri.org/IAuthenticateService/GetAccessToSystemResponse")]
        System.Threading.Tasks.Task<bool> GetAccessToSystemAsync(string systemToken, System.Nullable<int> idUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticateServiceChannel : Pe.GyM.Security.Account.SSOAuthenticateService.IAuthenticateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateServiceClient : System.ServiceModel.ClientBase<Pe.GyM.Security.Account.SSOAuthenticateService.IAuthenticateService>, Pe.GyM.Security.Account.SSOAuthenticateService.IAuthenticateService {
        
        public AuthenticateServiceClient() {
        }
        
        public AuthenticateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pe.GyM.Security.Account.SSOAuthenticateService.WebUser Authenticate(string UserName, string Password) {
            return base.Channel.Authenticate(UserName, Password);
        }
        
        public System.Threading.Tasks.Task<Pe.GyM.Security.Account.SSOAuthenticateService.WebUser> AuthenticateAsync(string UserName, string Password) {
            return base.Channel.AuthenticateAsync(UserName, Password);
        }
        
        public Pe.GyM.Security.Account.SSOAuthenticateService.WebUser GetUserByToken(string Token) {
            return base.Channel.GetUserByToken(Token);
        }
        
        public System.Threading.Tasks.Task<Pe.GyM.Security.Account.SSOAuthenticateService.WebUser> GetUserByTokenAsync(string Token) {
            return base.Channel.GetUserByTokenAsync(Token);
        }
        
        public bool IsUserLoggedIn(string Token) {
            return base.Channel.IsUserLoggedIn(Token);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserLoggedInAsync(string Token) {
            return base.Channel.IsUserLoggedInAsync(Token);
        }
        
        public bool IsValidRequest(string RedirectId) {
            return base.Channel.IsValidRequest(RedirectId);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidRequestAsync(string RedirectId) {
            return base.Channel.IsValidRequestAsync(RedirectId);
        }
        
        public Pe.GyM.Security.Account.SSOAuthenticateService.UserStatus GetUserStauts(string Token, string RequestId) {
            return base.Channel.GetUserStauts(Token, RequestId);
        }
        
        public System.Threading.Tasks.Task<Pe.GyM.Security.Account.SSOAuthenticateService.UserStatus> GetUserStautsAsync(string Token, string RequestId) {
            return base.Channel.GetUserStautsAsync(Token, RequestId);
        }
        
        public bool GetAccessToSystem(string systemToken, System.Nullable<int> idUser) {
            return base.Channel.GetAccessToSystem(systemToken, idUser);
        }
        
        public System.Threading.Tasks.Task<bool> GetAccessToSystemAsync(string systemToken, System.Nullable<int> idUser) {
            return base.Channel.GetAccessToSystemAsync(systemToken, idUser);
        }
    }
}
