//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Politicas.Presentacion.Recursos.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrabajadorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrabajadorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.Politicas.Presentacion.Recursos.General.TrabajadorResource", typeof(TrabajadorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string EtiquetaActivo {
            get {
                return ResourceManager.GetString("EtiquetaActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo.
        /// </summary>
        public static string EtiquetaAnexo {
            get {
                return ResourceManager.GetString("EtiquetaAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Materno.
        /// </summary>
        public static string EtiquetaApellidoMaterno {
            get {
                return ResourceManager.GetString("EtiquetaApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Paterno.
        /// </summary>
        public static string EtiquetaApellidoPaterno {
            get {
                return ResourceManager.GetString("EtiquetaApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string EtiquetaCargo {
            get {
                return ResourceManager.GetString("EtiquetaCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Identificación.
        /// </summary>
        public static string EtiquetaCodigoIdentificacion {
            get {
                return ResourceManager.GetString("EtiquetaCodigoIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        public static string EtiquetaCodigoTipoDocumento {
            get {
                return ResourceManager.GetString("EtiquetaCodigoTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string EtiquetaCorreoElectronico {
            get {
                return ResourceManager.GetString("EtiquetaCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        public static string EtiquetaDepartamento {
            get {
                return ResourceManager.GetString("EtiquetaDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de querer eliminar a los trabajadores seleccionados?.
        /// </summary>
        public static string EtiquetaEliminarDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaEliminarDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Matriz.
        /// </summary>
        public static string EtiquetaEmpresaMatriz {
            get {
                return ResourceManager.GetString("EtiquetaEmpresaMatriz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Fin.
        /// </summary>
        public static string EtiquetaFechaFin {
            get {
                return ResourceManager.GetString("EtiquetaFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Inicio.
        /// </summary>
        public static string EtiquetaFechaInicio {
            get {
                return ResourceManager.GetString("EtiquetaFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string EtiquetaNo {
            get {
                return ResourceManager.GetString("EtiquetaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string EtiquetaNombres {
            get {
                return ResourceManager.GetString("EtiquetaNombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Documento.
        /// </summary>
        public static string EtiquetaNumeroDocumentoIdentidad {
            get {
                return ResourceManager.GetString("EtiquetaNumeroDocumentoIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organización.
        /// </summary>
        public static string EtiquetaOrganizacion {
            get {
                return ResourceManager.GetString("EtiquetaOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto.
        /// </summary>
        public static string EtiquetaProyecto {
            get {
                return ResourceManager.GetString("EtiquetaProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        public static string EtiquetaSi {
            get {
                return ResourceManager.GetString("EtiquetaSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suplente.
        /// </summary>
        public static string EtiquetaSuplente {
            get {
                return ResourceManager.GetString("EtiquetaSuplente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Móvil.
        /// </summary>
        public static string EtiquetaTelefonoMovil {
            get {
                return ResourceManager.GetString("EtiquetaTelefonoMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Personal.
        /// </summary>
        public static string EtiquetaTelefonoPersonal {
            get {
                return ResourceManager.GetString("EtiquetaTelefonoPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono de Trabajo.
        /// </summary>
        public static string EtiquetaTelefonoTrabajo {
            get {
                return ResourceManager.GetString("EtiquetaTelefonoTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajador.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Reemplazo a.
        /// </summary>
        public static string EtiquetaTituloPrincipalSuplente {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipalSuplente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario Asignar Proyecto a.
        /// </summary>
        public static string EtiquetaTituloPrincipalTrabajadorUnidadOperativa {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipalTrabajadorUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los proyectos.
        /// </summary>
        public static string EtiquetaTodosLosProyectos {
            get {
                return ResourceManager.GetString("EtiquetaTodosLosProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo.
        /// </summary>
        public static string GridAnexo {
            get {
                return ResourceManager.GetString("GridAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Materno.
        /// </summary>
        public static string GridApellidoMaterno {
            get {
                return ResourceManager.GetString("GridApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Paterno.
        /// </summary>
        public static string GridApellidoPaterno {
            get {
                return ResourceManager.GetString("GridApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string GridCargo {
            get {
                return ResourceManager.GetString("GridCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación.
        /// </summary>
        public static string GridCodigoIdentificacion {
            get {
                return ResourceManager.GetString("GridCodigoIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        public static string GridCodigoTipoDocumento {
            get {
                return ResourceManager.GetString("GridCodigoTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string GridCorreoElectronico {
            get {
                return ResourceManager.GetString("GridCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        public static string GridDepartamento {
            get {
                return ResourceManager.GetString("GridDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string GridNombres {
            get {
                return ResourceManager.GetString("GridNombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Documento.
        /// </summary>
        public static string GridNumeroDocumentoIdentidad {
            get {
                return ResourceManager.GetString("GridNumeroDocumentoIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organización.
        /// </summary>
        public static string GridOrganizacion {
            get {
                return ResourceManager.GetString("GridOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Móvil.
        /// </summary>
        public static string GridTelefonoMovil {
            get {
                return ResourceManager.GetString("GridTelefonoMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Personal.
        /// </summary>
        public static string GridTelefonoPersonal {
            get {
                return ResourceManager.GetString("GridTelefonoPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Trabajo.
        /// </summary>
        public static string GridTelefonoTrabajo {
            get {
                return ResourceManager.GetString("GridTelefonoTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar un suplente.
        /// </summary>
        public static string MensajeErrorSuplente {
            get {
                return ResourceManager.GetString("MensajeErrorSuplente", resourceCulture);
            }
        }
    }
}
