//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Reportes.Recursos.BienesContrato {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BienesContrato {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BienesContrato() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Reportes.Recursos.BienesContrato.BienesContrato", typeof(BienesContrato).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código del Bien.
        /// </summary>
        public static string columnCodigoBien {
            get {
                return ResourceManager.GetString("columnCodigoBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Unidad Operativa.
        /// </summary>
        public static string columnCodigoUnidad {
            get {
                return ResourceManager.GetString("columnCodigoUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato Vigente.
        /// </summary>
        public static string columnContratoVigente {
            get {
                return ResourceManager.GetString("columnContratoVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string columnDescripcion {
            get {
                return ResourceManager.GetString("columnDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Adquisición.
        /// </summary>
        public static string columnFechaAdquisicion {
            get {
                return ResourceManager.GetString("columnFechaAdquisicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Fin del Contrato.
        /// </summary>
        public static string columnFechaFinContrato {
            get {
                return ResourceManager.GetString("columnFechaFinContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio del Contrato.
        /// </summary>
        public static string columnFechaInicioContrato {
            get {
                return ResourceManager.GetString("columnFechaInicioContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ítem.
        /// </summary>
        public static string columnItem {
            get {
                return ResourceManager.GetString("columnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string columnMarca {
            get {
                return ResourceManager.GetString("columnMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        public static string columnModelo {
            get {
                return ResourceManager.GetString("columnModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moneda del Contrato.
        /// </summary>
        public static string columnMonedaContrato {
            get {
                return ResourceManager.GetString("columnMonedaContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto del Contrato.
        /// </summary>
        public static string columnMontoContrato {
            get {
                return ResourceManager.GetString("columnMontoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Serie.
        /// </summary>
        public static string columnNumeroSerie {
            get {
                return ResourceManager.GetString("columnNumeroSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo.
        /// </summary>
        public static string columnPeriodo {
            get {
                return ResourceManager.GetString("columnPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plazo del Contrato.
        /// </summary>
        public static string columnPlazoContrato {
            get {
                return ResourceManager.GetString("columnPlazoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string columnProveedor {
            get {
                return ResourceManager.GetString("columnProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Bien.
        /// </summary>
        public static string columnTipoBien {
            get {
                return ResourceManager.GetString("columnTipoBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Periodo.
        /// </summary>
        public static string columnTipoPeriodo {
            get {
                return ResourceManager.GetString("columnTipoPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Tarifa.
        /// </summary>
        public static string columnTipoTarifa {
            get {
                return ResourceManager.GetString("columnTipoTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Organizacional.
        /// </summary>
        public static string columnUnidadOrganizacional {
            get {
                return ResourceManager.GetString("columnUnidadOrganizacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Residual.
        /// </summary>
        public static string columnValorResidual {
            get {
                return ResourceManager.GetString("columnValorResidual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor de Tarifa.
        /// </summary>
        public static string columnValorTarifa {
            get {
                return ResourceManager.GetString("columnValorTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vida útil.
        /// </summary>
        public static string columnVidaUtil {
            get {
                return ResourceManager.GetString("columnVidaUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Proveedor.
        /// </summary>
        public static string txtNombreProveedor {
            get {
                return ResourceManager.GetString("txtNombreProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Serie.
        /// </summary>
        public static string txtNumeroSerie {
            get {
                return ResourceManager.GetString("txtNumeroSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUC de Proveedor.
        /// </summary>
        public static string txtRucProveedor {
            get {
                return ResourceManager.GetString("txtRucProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Bien.
        /// </summary>
        public static string txtTipoBien {
            get {
                return ResourceManager.GetString("txtTipoBien", resourceCulture);
            }
        }
    }
}
