//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SAPProvService.ZWS_ZSGC_OBTPROVEEDORES")]
    public interface ZWS_ZSGC_OBTPROVEEDORES {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ZSGC_OBTPROVEEDORES no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_ZSGC_OBTPROVEEDORES:ZSGC_OBTPROVEEDORE" +
            "SRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESResponse1 ZSGC_OBTPROVEEDORES(Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_ZSGC_OBTPROVEEDORES:ZSGC_OBTPROVEEDORE" +
            "SRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESResponse1> ZSGC_OBTPROVEEDORESAsync(Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSGC_OBTPROVEEDORES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_BPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_BP {
            get {
                return this.i_BPField;
            }
            set {
                this.i_BPField = value;
                this.RaisePropertyChanged("I_BP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSGC_PROVEEDOR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDENT_FISCALField;
        
        private string nOMBRE_BPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDENT_FISCAL {
            get {
                return this.iDENT_FISCALField;
            }
            set {
                this.iDENT_FISCALField = value;
                this.RaisePropertyChanged("IDENT_FISCAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NOMBRE_BP {
            get {
                return this.nOMBRE_BPField;
            }
            set {
                this.nOMBRE_BPField = value;
                this.RaisePropertyChanged("NOMBRE_BP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSGC_OBTPROVEEDORESResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSGC_PROVEEDOR[] e_PROVEEDORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSGC_PROVEEDOR[] E_PROVEEDOR {
            get {
                return this.e_PROVEEDORField;
            }
            set {
                this.e_PROVEEDORField = value;
                this.RaisePropertyChanged("E_PROVEEDOR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSGC_OBTPROVEEDORESRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORES ZSGC_OBTPROVEEDORES;
        
        public ZSGC_OBTPROVEEDORESRequest() {
        }
        
        public ZSGC_OBTPROVEEDORESRequest(Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORES ZSGC_OBTPROVEEDORES) {
            this.ZSGC_OBTPROVEEDORES = ZSGC_OBTPROVEEDORES;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSGC_OBTPROVEEDORESResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESResponse ZSGC_OBTPROVEEDORESResponse;
        
        public ZSGC_OBTPROVEEDORESResponse1() {
        }
        
        public ZSGC_OBTPROVEEDORESResponse1(Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESResponse ZSGC_OBTPROVEEDORESResponse) {
            this.ZSGC_OBTPROVEEDORESResponse = ZSGC_OBTPROVEEDORESResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_ZSGC_OBTPROVEEDORESChannel : Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZWS_ZSGC_OBTPROVEEDORES, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_ZSGC_OBTPROVEEDORESClient : System.ServiceModel.ClientBase<Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZWS_ZSGC_OBTPROVEEDORES>, Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZWS_ZSGC_OBTPROVEEDORES {
        
        public ZWS_ZSGC_OBTPROVEEDORESClient() {
        }
        
        public ZWS_ZSGC_OBTPROVEEDORESClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_ZSGC_OBTPROVEEDORESClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZSGC_OBTPROVEEDORESClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZSGC_OBTPROVEEDORESClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESResponse1 Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZWS_ZSGC_OBTPROVEEDORES.ZSGC_OBTPROVEEDORES(Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESRequest request) {
            return base.Channel.ZSGC_OBTPROVEEDORES(request);
        }
        
        public Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESResponse ZSGC_OBTPROVEEDORES(Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORES ZSGC_OBTPROVEEDORES1) {
            Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESRequest inValue = new Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESRequest();
            inValue.ZSGC_OBTPROVEEDORES = ZSGC_OBTPROVEEDORES1;
            Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESResponse1 retVal = ((Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZWS_ZSGC_OBTPROVEEDORES)(this)).ZSGC_OBTPROVEEDORES(inValue);
            return retVal.ZSGC_OBTPROVEEDORESResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESResponse1> Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZWS_ZSGC_OBTPROVEEDORES.ZSGC_OBTPROVEEDORESAsync(Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESRequest request) {
            return base.Channel.ZSGC_OBTPROVEEDORESAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESResponse1> ZSGC_OBTPROVEEDORESAsync(Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORES ZSGC_OBTPROVEEDORES) {
            Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESRequest inValue = new Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZSGC_OBTPROVEEDORESRequest();
            inValue.ZSGC_OBTPROVEEDORES = ZSGC_OBTPROVEEDORES;
            return ((Pe.Stracon.SGC.Infraestructura.Proxy.SAPProvService.ZWS_ZSGC_OBTPROVEEDORES)(this)).ZSGC_OBTPROVEEDORESAsync(inValue);
        }
    }
}
