//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Reportes.Recursos.ContratoPendienteElaborar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContratoPendienteElaborar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContratoPendienteElaborar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Reportes.Recursos.ContratoPendienteElaborar.ContratoPendienteElabo" +
                            "rar", typeof(ContratoPendienteElaborar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string columnMoneda {
            get {
                return ResourceManager.GetString("columnMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto Acumulado.
        /// </summary>
        public static string columnMontoAcumulado {
            get {
                return ResourceManager.GetString("columnMontoAcumulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo Notificación.
        /// </summary>
        public static string columnPeriodoNotificacion {
            get {
                return ResourceManager.GetString("columnPeriodoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Orden.
        /// </summary>
        public static string columnTipoOrden {
            get {
                return ResourceManager.GetString("columnTipoOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string txtAbril {
            get {
                return ResourceManager.GetString("txtAbril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string txtAgosto {
            get {
                return ResourceManager.GetString("txtAgosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string txtAnio {
            get {
                return ResourceManager.GetString("txtAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diciembre.
        /// </summary>
        public static string txtDiciembre {
            get {
                return ResourceManager.GetString("txtDiciembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero.
        /// </summary>
        public static string txtEnero {
            get {
                return ResourceManager.GetString("txtEnero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febrero.
        /// </summary>
        public static string txtFebrero {
            get {
                return ResourceManager.GetString("txtFebrero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio.
        /// </summary>
        public static string txtJulio {
            get {
                return ResourceManager.GetString("txtJulio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junio.
        /// </summary>
        public static string txtJunio {
            get {
                return ResourceManager.GetString("txtJunio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        public static string txtMarzo {
            get {
                return ResourceManager.GetString("txtMarzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayo.
        /// </summary>
        public static string txtMayo {
            get {
                return ResourceManager.GetString("txtMayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        public static string txtMes {
            get {
                return ResourceManager.GetString("txtMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string txtMoneda {
            get {
                return ResourceManager.GetString("txtMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Proveedor.
        /// </summary>
        public static string txtNombreProveedor {
            get {
                return ResourceManager.GetString("txtNombreProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noviembre.
        /// </summary>
        public static string txtNoviembre {
            get {
                return ResourceManager.GetString("txtNoviembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octubre.
        /// </summary>
        public static string txtOctubre {
            get {
                return ResourceManager.GetString("txtOctubre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUC de Proveedor.
        /// </summary>
        public static string txtRucProveedor {
            get {
                return ResourceManager.GetString("txtRucProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setiembre.
        /// </summary>
        public static string txtSetiembre {
            get {
                return ResourceManager.GetString("txtSetiembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Orden.
        /// </summary>
        public static string txtTipoOrden {
            get {
                return ResourceManager.GetString("txtTipoOrden", resourceCulture);
            }
        }
    }
}
