//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Politicas.Presentacion.Recursos.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlantillaNotificacionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlantillaNotificacionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.Politicas.Presentacion.Recursos.General.PlantillaNotificacionResource", typeof(PlantillaNotificacionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        public static string EtiquetaAsunto {
            get {
                return ResourceManager.GetString("EtiquetaAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido.
        /// </summary>
        public static string EtiquetaContenido {
            get {
                return ResourceManager.GetString("EtiquetaContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatario.
        /// </summary>
        public static string EtiquetaDestinatario {
            get {
                return ResourceManager.GetString("EtiquetaDestinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatario en Copia.
        /// </summary>
        public static string EtiquetaDestinatarioCopia {
            get {
                return ResourceManager.GetString("EtiquetaDestinatarioCopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de Notificación.
        /// </summary>
        public static string EtiquetaPlantillaActiva {
            get {
                return ResourceManager.GetString("EtiquetaPlantillaActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla de Notificaciones.
        /// </summary>
        public static string EtiquetaTitulo {
            get {
                return ResourceManager.GetString("EtiquetaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        public static string GridAsunto {
            get {
                return ResourceManager.GetString("GridAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido.
        /// </summary>
        public static string GridContenido {
            get {
                return ResourceManager.GetString("GridContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatario.
        /// </summary>
        public static string GridDestinatario {
            get {
                return ResourceManager.GetString("GridDestinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatario en Copia.
        /// </summary>
        public static string GridDestinatarioCopia {
            get {
                return ResourceManager.GetString("GridDestinatarioCopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificación Activa.
        /// </summary>
        public static string GridPlantillaActiva {
            get {
                return ResourceManager.GetString("GridPlantillaActiva", resourceCulture);
            }
        }
    }
}
