//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Politicas.Presentacion.Recursos.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SeccionParametroResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeccionParametroResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.Politicas.Presentacion.Recursos.General.SeccionParametroResource", typeof(SeccionParametroResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string EtiquetaCodigoIdentificador {
            get {
                return ResourceManager.GetString("EtiquetaCodigoIdentificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string EtiquetaDescripcionParametro {
            get {
                return ResourceManager.GetString("EtiquetaDescripcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario Sección de Parámetro.
        /// </summary>
        public static string EtiquetaDlgFormularioSeccionParametrosGenerales {
            get {
                return ResourceManager.GetString("EtiquetaDlgFormularioSeccionParametrosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de eliminar los parámetros seleccionados?.
        /// </summary>
        public static string EtiquetaDlgMsgEliminar {
            get {
                return ResourceManager.GetString("EtiquetaDlgMsgEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de querer eliminar los registros realizados?.
        /// </summary>
        public static string EtiquetaMessageDlgEstaSeguro {
            get {
                return ResourceManager.GetString("EtiquetaMessageDlgEstaSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de querer grabar los cambios realizados?.
        /// </summary>
        public static string EtiquetaMessageDlgEstaSeguroGrabar {
            get {
                return ResourceManager.GetString("EtiquetaMessageDlgEstaSeguroGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string EtiquetaNombreParametro {
            get {
                return ResourceManager.GetString("EtiquetaNombreParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string EtiquetaNombreSeccion {
            get {
                return ResourceManager.GetString("EtiquetaNombreSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una sección con el mismo nombre.
        /// </summary>
        public static string EtiquetaNombreSeccionRepetido {
            get {
                return ResourceManager.GetString("EtiquetaNombreSeccionRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatorio.
        /// </summary>
        public static string EtiquetaObligatorio {
            get {
                return ResourceManager.GetString("EtiquetaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro.
        /// </summary>
        public static string EtiquetaParametro {
            get {
                return ResourceManager.GetString("EtiquetaParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro de Empresa.
        /// </summary>
        public static string EtiquetaParametroEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaParametroEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string EtiquetaParametroEmpresaNo {
            get {
                return ResourceManager.GetString("EtiquetaParametroEmpresaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string EtiquetaParametroEmpresaSi {
            get {
                return ResourceManager.GetString("EtiquetaParametroEmpresaSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string EtiquetaParametroEmpresaTodos {
            get {
                return ResourceManager.GetString("EtiquetaParametroEmpresaTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro Relacionado.
        /// </summary>
        public static string EtiquetaParametroRelacionado {
            get {
                return ResourceManager.GetString("EtiquetaParametroRelacionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite Modificar.
        /// </summary>
        public static string EtiquetaPermiteModificar {
            get {
                return ResourceManager.GetString("EtiquetaPermiteModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados de la Busqueda.
        /// </summary>
        public static string EtiquetaResultadosBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección Relacionada.
        /// </summary>
        public static string EtiquetaSeccionRelacionada {
            get {
                return ResourceManager.GetString("EtiquetaSeccionRelacionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección Relacionada a Mostrar.
        /// </summary>
        public static string EtiquetaSeccionRelacionadaVisible {
            get {
                return ResourceManager.GetString("EtiquetaSeccionRelacionadaVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string EtiquetaSistema {
            get {
                return ResourceManager.GetString("EtiquetaSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Dato.
        /// </summary>
        public static string EtiquetaTipoDato {
            get {
                return ResourceManager.GetString("EtiquetaTipoDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Parámetro.
        /// </summary>
        public static string EtiquetaTipoParametro {
            get {
                return ResourceManager.GetString("EtiquetaTipoParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string EtiquetaTituloDlgConfirmar {
            get {
                return ResourceManager.GetString("EtiquetaTituloDlgConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Parámetro.
        /// </summary>
        public static string EtiquetaTituloEliminar {
            get {
                return ResourceManager.GetString("EtiquetaTituloEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Secciones.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string GridSeleccionar {
            get {
                return ResourceManager.GetString("GridSeleccionar", resourceCulture);
            }
        }
    }
}
