//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Politicas.Presentacion.Recursos.Base {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenericoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericoResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.Politicas.Presentacion.Recursos.Base.GenericoResource", typeof(GenericoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string BotonAceptar {
            get {
                return ResourceManager.GetString("BotonAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string BotonAceptar1 {
            get {
                return ResourceManager.GetString("BotonAceptar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string BotonAgregar {
            get {
                return ResourceManager.GetString("BotonAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string BotonAgregar1 {
            get {
                return ResourceManager.GetString("BotonAgregar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string BotonAñadir {
            get {
                return ResourceManager.GetString("BotonAñadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string BotonAñadir1 {
            get {
                return ResourceManager.GetString("BotonAñadir1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string BotonAnterior {
            get {
                return ResourceManager.GetString("BotonAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplica.
        /// </summary>
        public static string BotonAplica {
            get {
                return ResourceManager.GetString("BotonAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string BotonAprobar {
            get {
                return ResourceManager.GetString("BotonAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizar.
        /// </summary>
        public static string BotonAutorizar {
            get {
                return ResourceManager.GetString("BotonAutorizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string BotonBuscar {
            get {
                return ResourceManager.GetString("BotonBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string BotonBuscar1 {
            get {
                return ResourceManager.GetString("BotonBuscar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Usuario en AD.
        /// </summary>
        public static string BotonBuscarUsuarioAD {
            get {
                return ResourceManager.GetString("BotonBuscarUsuarioAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string BotonCancelar {
            get {
                return ResourceManager.GetString("BotonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string BotonCancelar1 {
            get {
                return ResourceManager.GetString("BotonCancelar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string BotonCerrar {
            get {
                return ResourceManager.GetString("BotonCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string BotonCerrar1 {
            get {
                return ResourceManager.GetString("BotonCerrar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string BotonCerrarSesion {
            get {
                return ResourceManager.GetString("BotonCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string BotonCerrarSesion1 {
            get {
                return ResourceManager.GetString("BotonCerrarSesion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        public static string BotonCopiar {
            get {
                return ResourceManager.GetString("BotonCopiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denegar.
        /// </summary>
        public static string BotonDenegar {
            get {
                return ResourceManager.GetString("BotonDenegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string BotonEliminar {
            get {
                return ResourceManager.GetString("BotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string BotonEliminar1 {
            get {
                return ResourceManager.GetString("BotonEliminar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabar.
        /// </summary>
        public static string BotonGrabar {
            get {
                return ResourceManager.GetString("BotonGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabar.
        /// </summary>
        public static string BotonGrabar1 {
            get {
                return ResourceManager.GetString("BotonGrabar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string BotonLimpiar {
            get {
                return ResourceManager.GetString("BotonLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string BotonLimpiar1 {
            get {
                return ResourceManager.GetString("BotonLimpiar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar.
        /// </summary>
        public static string BotonMostrar {
            get {
                return ResourceManager.GetString("BotonMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar.
        /// </summary>
        public static string BotonMostrar1 {
            get {
                return ResourceManager.GetString("BotonMostrar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Aplica.
        /// </summary>
        public static string BotonNoAplica {
            get {
                return ResourceManager.GetString("BotonNoAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string BotonRechazar {
            get {
                return ResourceManager.GetString("BotonRechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responder.
        /// </summary>
        public static string BotonResponder {
            get {
                return ResourceManager.GetString("BotonResponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string BotonSiguiente {
            get {
                return ResourceManager.GetString("BotonSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista Previa.
        /// </summary>
        public static string BotonVistaPrevia {
            get {
                return ResourceManager.GetString("BotonVistaPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string BtnRegresar {
            get {
                return ResourceManager.GetString("BtnRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string BtnRegresar1 {
            get {
                return ResourceManager.GetString("BtnRegresar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTIVA.
        /// </summary>
        public static string EtiquetaActiva {
            get {
                return ResourceManager.GetString("EtiquetaActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTIVA.
        /// </summary>
        public static string EtiquetaActiva1 {
            get {
                return ResourceManager.GetString("EtiquetaActiva1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar proyecto.
        /// </summary>
        public static string EtiquetaAsignarProyecto {
            get {
                return ResourceManager.GetString("EtiquetaAsignarProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar usuario de consulta.
        /// </summary>
        public static string EtiquetaAsignarResponsable {
            get {
                return ResourceManager.GetString("EtiquetaAsignarResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar Staff.
        /// </summary>
        public static string EtiquetaAsignarStaff {
            get {
                return ResourceManager.GetString("EtiquetaAsignarStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar reemplazo.
        /// </summary>
        public static string EtiquetaAsignarSuplente {
            get {
                return ResourceManager.GetString("EtiquetaAsignarSuplente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string EtiquetaCorreoElectronico {
            get {
                return ResourceManager.GetString("EtiquetaCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electronico.
        /// </summary>
        public static string EtiquetaCorreoElectronico1 {
            get {
                return ResourceManager.GetString("EtiquetaCorreoElectronico1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EtiquetaEditar {
            get {
                return ResourceManager.GetString("EtiquetaEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EtiquetaEditar1 {
            get {
                return ResourceManager.GetString("EtiquetaEditar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string EtiquetaEliminar {
            get {
                return ResourceManager.GetString("EtiquetaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string EtiquetaEliminar1 {
            get {
                return ResourceManager.GetString("EtiquetaEliminar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string EtiquetaFecha {
            get {
                return ResourceManager.GetString("EtiquetaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *** FIN DE {0} ***.
        /// </summary>
        public static string EtiquetaFinReporte {
            get {
                return ResourceManager.GetString("EtiquetaFinReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar archivo.
        /// </summary>
        public static string EtiquetaGridFileUpload {
            get {
                return ResourceManager.GetString("EtiquetaGridFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar Archivo.
        /// </summary>
        public static string EtiquetaGridFileUpload1 {
            get {
                return ResourceManager.GetString("EtiquetaGridFileUpload1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INACTIVA.
        /// </summary>
        public static string EtiquetaInactiva {
            get {
                return ResourceManager.GetString("EtiquetaInactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INACTIVA.
        /// </summary>
        public static string EtiquetaInactiva1 {
            get {
                return ResourceManager.GetString("EtiquetaInactiva1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO.
        /// </summary>
        public static string EtiquetaNo {
            get {
                return ResourceManager.GetString("EtiquetaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO.
        /// </summary>
        public static string EtiquetaNo1 {
            get {
                return ResourceManager.GetString("EtiquetaNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SISTEMA DE GESTION DE POLÍTICAS DE STRACON.
        /// </summary>
        public static string EtiquetaNombreSistema {
            get {
                return ResourceManager.GetString("EtiquetaNombreSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SISTEMA DE GESTION DE CIERRE CONTABLE.
        /// </summary>
        public static string EtiquetaNombreSistemaContable {
            get {
                return ResourceManager.GetString("EtiquetaNombreSistemaContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SISTEMA DE GESTION CONTRACTUAL.
        /// </summary>
        public static string EtiquetaNombreSistemaContractual {
            get {
                return ResourceManager.GetString("EtiquetaNombreSistemaContractual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        public static string EtiquetaNotificaciones {
            get {
                return ResourceManager.GetString("EtiquetaNotificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificar.
        /// </summary>
        public static string EtiquetaNotificar {
            get {
                return ResourceManager.GetString("EtiquetaNotificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        public static string EtiquetaNumero {
            get {
                return ResourceManager.GetString("EtiquetaNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados de Búsqueda.
        /// </summary>
        public static string EtiquetaResultadosBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados de Búsqueda.
        /// </summary>
        public static string EtiquetaResultadosBusqueda1 {
            get {
                return ResourceManager.GetString("EtiquetaResultadosBusqueda1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (SELECCIONAR).
        /// </summary>
        public static string EtiquetaSeleccionar {
            get {
                return ResourceManager.GetString("EtiquetaSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (SELECCIONAR).
        /// </summary>
        public static string EtiquetaSeleccionar1 {
            get {
                return ResourceManager.GetString("EtiquetaSeleccionar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SI.
        /// </summary>
        public static string EtiquetaSi {
            get {
                return ResourceManager.GetString("EtiquetaSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SI.
        /// </summary>
        public static string EtiquetaSi1 {
            get {
                return ResourceManager.GetString("EtiquetaSi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anexo.
        /// </summary>
        public static string EtiquetaTelefonoAnexo {
            get {
                return ResourceManager.GetString("EtiquetaTelefonoAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Movil.
        /// </summary>
        public static string EtiquetaTelefonoMovil {
            get {
                return ResourceManager.GetString("EtiquetaTelefonoMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Trabajo.
        /// </summary>
        public static string EtiquetaTelefonoTrabajo {
            get {
                return ResourceManager.GetString("EtiquetaTelefonoTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        public static string EtiquetaTexto {
            get {
                return ResourceManager.GetString("EtiquetaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Común.
        /// </summary>
        public static string EtiquetaTipoParametroComun {
            get {
                return ResourceManager.GetString("EtiquetaTipoParametroComun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcional.
        /// </summary>
        public static string EtiquetaTipoParametroFuncional {
            get {
                return ResourceManager.GetString("EtiquetaTipoParametroFuncional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        public static string EtiquetaTipoParametroSistema {
            get {
                return ResourceManager.GetString("EtiquetaTipoParametroSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string EtiquetaTituloConfirmar {
            get {
                return ResourceManager.GetString("EtiquetaTituloConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string EtiquetaTituloConfirmar1 {
            get {
                return ResourceManager.GetString("EtiquetaTituloConfirmar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (TODOS).
        /// </summary>
        public static string EtiquetaTodos {
            get {
                return ResourceManager.GetString("EtiquetaTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (TODOS).
        /// </summary>
        public static string EtiquetaTodos1 {
            get {
                return ResourceManager.GetString("EtiquetaTodos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vencido.
        /// </summary>
        public static string EtiquetaVencido {
            get {
                return ResourceManager.GetString("EtiquetaVencido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Firma.
        /// </summary>
        public static string EtiquetaVerFirma {
            get {
                return ResourceManager.GetString("EtiquetaVerFirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar :.
        /// </summary>
        public static string EtiquetaVerificar {
            get {
                return ResourceManager.GetString("EtiquetaVerificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente.
        /// </summary>
        public static string EtiquetaVigente {
            get {
                return ResourceManager.GetString("EtiquetaVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string GridAcciones {
            get {
                return ResourceManager.GetString("GridAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string GridAcciones1 {
            get {
                return ResourceManager.GetString("GridAcciones1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AgregarVariable.
        /// </summary>
        public static string GridAgregarVariable {
            get {
                return ResourceManager.GetString("GridAgregarVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string GridAprobar {
            get {
                return ResourceManager.GetString("GridAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar.
        /// </summary>
        public static string GridConsulta {
            get {
                return ResourceManager.GetString("GridConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controles.
        /// </summary>
        public static string GridControles {
            get {
                return ResourceManager.GetString("GridControles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controles.
        /// </summary>
        public static string GridControles1 {
            get {
                return ResourceManager.GetString("GridControles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        public static string GridCopiar {
            get {
                return ResourceManager.GetString("GridCopiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar Estadios.
        /// </summary>
        public static string GridCopiarEstadio {
            get {
                return ResourceManager.GetString("GridCopiarEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadios.
        /// </summary>
        public static string GridEstadios {
            get {
                return ResourceManager.GetString("GridEstadios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observar.
        /// </summary>
        public static string GridObservacion {
            get {
                return ResourceManager.GetString("GridObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Párrafos.
        /// </summary>
        public static string GridParrafo {
            get {
                return ResourceManager.GetString("GridParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pdf.
        /// </summary>
        public static string GridPdf {
            get {
                return ResourceManager.GetString("GridPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Predecesora.
        /// </summary>
        public static string GridPredecesora {
            get {
                return ResourceManager.GetString("GridPredecesora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        public static string GridSistema {
            get {
                return ResourceManager.GetString("GridSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string GridUsuario {
            get {
                return ResourceManager.GetString("GridUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SISTEMA DE GESTIÓN CONTRACTUAL.
        /// </summary>
        public static string NombreSistema {
            get {
                return ResourceManager.GetString("NombreSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Registros.
        /// </summary>
        public static string TituloEliminar {
            get {
                return ResourceManager.GetString("TituloEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar al menos un valor.
        /// </summary>
        public static string ValidacionAlmenosUno {
            get {
                return ResourceManager.GetString("ValidacionAlmenosUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningún Campo puede tener números negativos.
        /// </summary>
        public static string ValidacionNumeroNegativo {
            get {
                return ResourceManager.GetString("ValidacionNumeroNegativo", resourceCulture);
            }
        }
    }
}
