//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Aplicacion.Core.Message {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajesSistema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesSistema() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Aplicacion.Core.Message.MensajesSistema", typeof(MensajesSistema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede copiar los estadios de un mismo registro.
        /// </summary>
        public static string CopiarEstadioIgual {
            get {
                return ResourceManager.GetString("CopiarEstadioIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro no existe.
        /// </summary>
        public static string CopiarEstadioNoExiste {
            get {
                return ResourceManager.GetString("CopiarEstadioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija otro registro, este no contiene estadios.
        /// </summary>
        public static string CopiarEstadioNoTiene {
            get {
                return ResourceManager.GetString("CopiarEstadioNoTiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado. Inténtelo nuevamente..
        /// </summary>
        public static string EtiquetaError {
            get {
                return ResourceManager.GetString("EtiquetaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los firmantes ya están completos o el orden de firmante ya existe..
        /// </summary>
        public static string FirmanteNoValido {
            get {
                return ResourceManager.GetString("FirmanteNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un estadio con la misma Descripción..
        /// </summary>
        public static string FlujoAprobacionEstadioDescripcionExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionEstadioDescripcionExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un estadio con los mismos datos de Orden de Prioridad y Descripción.
        /// </summary>
        public static string FlujoAprobacionEstadioExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionEstadioExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un estadio con el mismo orden de prioridad.
        /// </summary>
        public static string FlujoAprobacionEstadioOrdenExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionEstadioOrdenExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un flujo de aprobación con los mismos datos..
        /// </summary>
        public static string FlujoAprobacionExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado un Flujo de Aprobación para la Forma de Edición {0}..
        /// </summary>
        public static string FlujoAprobacionFormaEdicionNoExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionFormaEdicionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un Flujo de Aprobación con la Unidad Operativa, Tipo de Contrato, Tipo de Requerimiento ingresado..
        /// </summary>
        public static string FlujoAprobacionNoExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un Flujo de Aprobación con la Unidad Operativa, Tipo de Contrato, Tipo de Requerimiento y Forma de Edición ingresado..
        /// </summary>
        public static string FlujoAprobacionNoExisteReporte {
            get {
                return ResourceManager.GetString("FlujoAprobacionNoExisteReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe establecer un Orden mayor a 1..
        /// </summary>
        public static string FlujoAprobacionOrdenIgualUno {
            get {
                return ResourceManager.GetString("FlujoAprobacionOrdenIgualUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede registrar una combinación ya existente..
        /// </summary>
        public static string PlantillaExiste {
            get {
                return ResourceManager.GetString("PlantillaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede registrar una Fecha de Inicio de Vigencia menor a la que ya existe..
        /// </summary>
        public static string PlantillaFechaInicioVigenciaMenor {
            get {
                return ResourceManager.GetString("PlantillaFechaInicioVigenciaMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato de la Fecha de Inicio de Vigencia es incorrecto..
        /// </summary>
        public static string PlantillaFechaInicioVigenciIncorrecto {
            get {
                return ResourceManager.GetString("PlantillaFechaInicioVigenciIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una Plantilla ni un Flujo de Aprobación para la combinación ingresada..
        /// </summary>
        public static string PlantillaFlujoAprobacionNoExiste {
            get {
                return ResourceManager.GetString("PlantillaFlujoAprobacionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar, existen contratos asociados a esta plantilla..
        /// </summary>
        public static string PlantillaNoEliminar {
            get {
                return ResourceManager.GetString("PlantillaNoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una Plantilla con el Tipo de Servicio, Tipo de Requerimiento, Tipo de Documento y Tipo Adhesión ingresado..
        /// </summary>
        public static string PlantillaNoExiste {
            get {
                return ResourceManager.GetString("PlantillaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar, existen contratos asociados a esta plantilla..
        /// </summary>
        public static string PlantillaNoModificar {
            get {
                return ResourceManager.GetString("PlantillaNoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El orden de la nota ya se encuentra registrado para esta plantilla..
        /// </summary>
        public static string PlantillaNotaOrdenExiste {
            get {
                return ResourceManager.GetString("PlantillaNotaOrdenExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un Párrafo con el mismo Orden y Título para la Plantilla..
        /// </summary>
        public static string PlantillaParrafoExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un Párrafo para la Plantilla seleccionada..
        /// </summary>
        public static string PlantillaParrafoNoExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Orden del Párrafo ya se encuentra registrada para esta Plantilla..
        /// </summary>
        public static string PlantillaParrafoOrdenExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoOrdenExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Título del Párrafo ya se encuentra registrada para esta Plantilla..
        /// </summary>
        public static string PlantillaParrafoTituloExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoTituloExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa Y  Fecha planificada, no pueden tener datos iguales..
        /// </summary>
        public static string ProcesoAuditoriaExiste {
            get {
                return ResourceManager.GetString("ProcesoAuditoriaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de moneda seleccionado no es el mismo que del contrato principal, para evitar errores en el monto acumulado debe seleccionar el tipo de moneda correcto..
        /// </summary>
        public static string ValidaMoneda {
            get {
                return ResourceManager.GetString("ValidaMoneda", resourceCulture);
            }
        }
    }
}
