//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Presentacion.Recursos.Contractual {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsultaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsultaResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Presentacion.Recursos.Contractual.ConsultaResource", typeof(ConsultaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adicional.
        /// </summary>
        public static string EtiquetaAdicional {
            get {
                return ResourceManager.GetString("EtiquetaAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        public static string EtiquetaArea {
            get {
                return ResourceManager.GetString("EtiquetaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenido.
        /// </summary>
        public static string EtiquetaContenido {
            get {
                return ResourceManager.GetString("EtiquetaContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Consulta.
        /// </summary>
        public static string EtiquetaDlgTituloEliminar {
            get {
                return ResourceManager.GetString("EtiquetaDlgTituloEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string EtiquetaEstado {
            get {
                return ResourceManager.GetString("EtiquetaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es Válido.
        /// </summary>
        public static string EtiquetaEsValido {
            get {
                return ResourceManager.GetString("EtiquetaEsValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remitente Original.
        /// </summary>
        public static string EtiquetaNombreRemitenteOriginal {
            get {
                return ResourceManager.GetString("EtiquetaNombreRemitenteOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar A.
        /// </summary>
        public static string EtiquetaReenviarA {
            get {
                return ResourceManager.GetString("EtiquetaReenviarA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remitente.
        /// </summary>
        public static string EtiquetaRemitente {
            get {
                return ResourceManager.GetString("EtiquetaRemitente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta.
        /// </summary>
        public static string EtiquetaRespuesta {
            get {
                return ResourceManager.GetString("EtiquetaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Consulta.
        /// </summary>
        public static string EtiquetaTitulo {
            get {
                return ResourceManager.GetString("EtiquetaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar Consulta.
        /// </summary>
        public static string EtiquetaTituloReenviar {
            get {
                return ResourceManager.GetString("EtiquetaTituloReenviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responder Consulta.
        /// </summary>
        public static string EtiquetaTituloResponder {
            get {
                return ResourceManager.GetString("EtiquetaTituloResponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string EtiquetaUnidadOperativa {
            get {
                return ResourceManager.GetString("EtiquetaUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizar Consulta.
        /// </summary>
        public static string EtiquetaVisualizarConsulta {
            get {
                return ResourceManager.GetString("EtiquetaVisualizarConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto.
        /// </summary>
        public static string GridAsunto {
            get {
                return ResourceManager.GetString("GridAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días Sin Respuesta.
        /// </summary>
        public static string GridDiaSinEnvio {
            get {
                return ResourceManager.GetString("GridDiaSinEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string GridEstado {
            get {
                return ResourceManager.GetString("GridEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Envío.
        /// </summary>
        public static string GridFechaEnvio {
            get {
                return ResourceManager.GetString("GridFechaEnvio", resourceCulture);
            }
        }
    }
}
