//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Presentacion.Recursos.Contractual {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FlujoAprobacionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlujoAprobacionResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Presentacion.Recursos.Contractual.FlujoAprobacionResource", typeof(FlujoAprobacionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualiza Número de Contrato.
        /// </summary>
        public static string EtiquetaActualizaNumeroContrato {
            get {
                return ResourceManager.GetString("EtiquetaActualizaNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplica Monto Mínimo.
        /// </summary>
        public static string EtiquetaAplicaMontoMinimo {
            get {
                return ResourceManager.GetString("EtiquetaAplicaMontoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo de Representante.
        /// </summary>
        public static string EtiquetaCargoRepresentante {
            get {
                return ResourceManager.GetString("EtiquetaCargoRepresentante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato Principal.
        /// </summary>
        public static string EtiquetaContratoPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaContratoPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiando...
        /// </summary>
        public static string EtiquetaCopiando {
            get {
                return ResourceManager.GetString("EtiquetaCopiando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Estadio.
        /// </summary>
        public static string EtiquetaDescripcionEstadio {
            get {
                return ResourceManager.GetString("EtiquetaDescripcionEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de la Modificación Solicitada.
        /// </summary>
        public static string EtiquetaDescripcionModificacionSolicitada {
            get {
                return ResourceManager.GetString("EtiquetaDescripcionModificacionSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días de Atención.
        /// </summary>
        public static string EtiquetaDiasAtencion {
            get {
                return ResourceManager.GetString("EtiquetaDiasAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Fin.
        /// </summary>
        public static string EtiquetaFechaFin {
            get {
                return ResourceManager.GetString("EtiquetaFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio.
        /// </summary>
        public static string EtiquetaFechaInicio {
            get {
                return ResourceManager.GetString("EtiquetaFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Primera Entrega.
        /// </summary>
        public static string EtiquetaFechaPrimeraEntrega {
            get {
                return ResourceManager.GetString("EtiquetaFechaPrimeraEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Ultima Entrega.
        /// </summary>
        public static string EtiquetaFechaUltimaEntrega {
            get {
                return ResourceManager.GetString("EtiquetaFechaUltimaEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de Edición.
        /// </summary>
        public static string EtiquetaFormaEdicion {
            get {
                return ResourceManager.GetString("EtiquetaFormaEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de Pago.
        /// </summary>
        public static string EtiquetaFormaPago {
            get {
                return ResourceManager.GetString("EtiquetaFormaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Estadio.
        /// </summary>
        public static string EtiquetaFormularioEstadio {
            get {
                return ResourceManager.GetString("EtiquetaFormularioEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Flujo de Aprobación.
        /// </summary>
        public static string EtiquetaFormularioFlujoAprobacion {
            get {
                return ResourceManager.GetString("EtiquetaFormularioFlujoAprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas de Atención.
        /// </summary>
        public static string EtiquetaHorasAtencion {
            get {
                return ResourceManager.GetString("EtiquetaHorasAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        public static string EtiquetaImagen {
            get {
                return ResourceManager.GetString("EtiquetaImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir Visto.
        /// </summary>
        public static string EtiquetaIncluirVisto {
            get {
                return ResourceManager.GetString("EtiquetaIncluirVisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es Firmante.
        /// </summary>
        public static string EtiquetaIndicadorEsFirmante {
            get {
                return ResourceManager.GetString("EtiquetaIndicadorEsFirmante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informados.
        /// </summary>
        public static string EtiquetaInformados {
            get {
                return ResourceManager.GetString("EtiquetaInformados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad Registro.
        /// </summary>
        public static string EtiquetaLocalidadRegistro {
            get {
                return ResourceManager.GetString("EtiquetaLocalidadRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto de Adelanto.
        /// </summary>
        public static string EtiquetaMontoAdelanto {
            get {
                return ResourceManager.GetString("EtiquetaMontoAdelanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto del Contrato.
        /// </summary>
        public static string EtiquetaMontoContrato {
            get {
                return ResourceManager.GetString("EtiquetaMontoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplica Monto Mínimo.
        /// </summary>
        public static string EtiquetaMontoMinimo {
            get {
                return ResourceManager.GetString("EtiquetaMontoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Cuotas.
        /// </summary>
        public static string EtiquetaNumeroCuotas {
            get {
                return ResourceManager.GetString("EtiquetaNumeroCuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden de Prioridad.
        /// </summary>
        public static string EtiquetaOrdenPrioridad {
            get {
                return ResourceManager.GetString("EtiquetaOrdenPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Párrafo.
        /// </summary>
        public static string EtiquetaParrafo {
            get {
                return ResourceManager.GetString("EtiquetaParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite Carga.
        /// </summary>
        public static string EtiquetaPermiteCarga {
            get {
                return ResourceManager.GetString("EtiquetaPermiteCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Firmante.
        /// </summary>
        public static string EtiquetaPrimerFirmante {
            get {
                return ResourceManager.GetString("EtiquetaPrimerFirmante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Firmante Vinculada.
        /// </summary>
        public static string EtiquetaPrimerFirmanteVinculada {
            get {
                return ResourceManager.GetString("EtiquetaPrimerFirmanteVinculada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string EtiquetaProveedor {
            get {
                return ResourceManager.GetString("EtiquetaProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string EtiquetaResponsable {
            get {
                return ResourceManager.GetString("EtiquetaResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo Firmante.
        /// </summary>
        public static string EtiquetaSegundoFirmante {
            get {
                return ResourceManager.GetString("EtiquetaSegundoFirmante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo Firmante Vinculada.
        /// </summary>
        public static string EtiquetaSegundoFirmanteVinculada {
            get {
                return ResourceManager.GetString("EtiquetaSegundoFirmanteVinculada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar Modificación.
        /// </summary>
        public static string EtiquetaSolicitarModificacion {
            get {
                return ResourceManager.GetString("EtiquetaSolicitarModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Contrato.
        /// </summary>
        public static string EtiquetaTipoContrato {
            get {
                return ResourceManager.GetString("EtiquetaTipoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Servicio.
        /// </summary>
        public static string EtiquetaTipoServicio {
            get {
                return ResourceManager.GetString("EtiquetaTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar Estadios de Flujo de Aprobación.
        /// </summary>
        public static string EtiquetaTituloModalCopiarEstadio {
            get {
                return ResourceManager.GetString("EtiquetaTituloModalCopiarEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flujo de Aprobación.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadios.
        /// </summary>
        public static string EtiquetatTituloEstadios {
            get {
                return ResourceManager.GetString("EtiquetatTituloEstadios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string EtiquetaUnidadOperativa {
            get {
                return ResourceManager.GetString("EtiquetaUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Versión Oficial.
        /// </summary>
        public static string EtiquetaVersionOficial {
            get {
                return ResourceManager.GetString("EtiquetaVersionOficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista Previa.
        /// </summary>
        public static string EtiquetaVistaPrevia {
            get {
                return ResourceManager.GetString("EtiquetaVistaPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualiza Número de Contrato.
        /// </summary>
        public static string GridActualizaNumeroContrato {
            get {
                return ResourceManager.GetString("GridActualizaNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplica Monto Minimo.
        /// </summary>
        public static string GridAplicaMontoMinimo {
            get {
                return ResourceManager.GetString("GridAplicaMontoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite Carga.
        /// </summary>
        public static string GridAplicaPermiteCarga {
            get {
                return ResourceManager.GetString("GridAplicaPermiteCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión Oficial.
        /// </summary>
        public static string GridAplicaVersionOficial {
            get {
                return ResourceManager.GetString("GridAplicaVersionOficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días de Atencion.
        /// </summary>
        public static string GridDiasAtencion {
            get {
                return ResourceManager.GetString("GridDiasAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadio.
        /// </summary>
        public static string GridEstadio {
            get {
                return ResourceManager.GetString("GridEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadios.
        /// </summary>
        public static string GridEstadios {
            get {
                return ResourceManager.GetString("GridEstadios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de Edición.
        /// </summary>
        public static string GridFormaEdicion {
            get {
                return ResourceManager.GetString("GridFormaEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas de Atención.
        /// </summary>
        public static string GridHorasAtencion {
            get {
                return ResourceManager.GetString("GridHorasAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplica Monto Mínimo.
        /// </summary>
        public static string GridIndicadorAplicaMontoMinimo {
            get {
                return ResourceManager.GetString("GridIndicadorAplicaMontoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informados.
        /// </summary>
        public static string GridInformados {
            get {
                return ResourceManager.GetString("GridInformados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        public static string GridOrden {
            get {
                return ResourceManager.GetString("GridOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Firmante.
        /// </summary>
        public static string GridPrimerFirmante {
            get {
                return ResourceManager.GetString("GridPrimerFirmante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string GridResponsable {
            get {
                return ResourceManager.GetString("GridResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo Firmante.
        /// </summary>
        public static string GridSegundoFirmante {
            get {
                return ResourceManager.GetString("GridSegundoFirmante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Contrato.
        /// </summary>
        public static string GridTipoContrato {
            get {
                return ResourceManager.GetString("GridTipoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Servicio.
        /// </summary>
        public static string GridTipoServicio {
            get {
                return ResourceManager.GetString("GridTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string GridUnidadOperativa {
            get {
                return ResourceManager.GetString("GridUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está seguro que desea Copiar los estadios.
        /// </summary>
        public static string MensajeCopiando {
            get {
                return ResourceManager.GetString("MensajeCopiando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al Responsable..
        /// </summary>
        public static string MensajeErrorResponsable {
            get {
                return ResourceManager.GetString("MensajeErrorResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar: Dias de Atención, Debe Ingresar valores entre 0 y 99.
        /// </summary>
        public static string ValidarDiasAtencionEntre {
            get {
                return ResourceManager.GetString("ValidarDiasAtencionEntre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar: Horas de Atención, Debe Ingresar valores entre 1 y 23.
        /// </summary>
        public static string ValidarHorasAtencionEntre {
            get {
                return ResourceManager.GetString("ValidarHorasAtencionEntre", resourceCulture);
            }
        }
    }
}
