//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Presentacion.Recursos.Contractual {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReporteListadoContratoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReporteListadoContratoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Presentacion.Recursos.Contractual.ReporteListadoContratoResource", typeof(ReporteListadoContratoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string EtiquetaDesde {
            get {
                return ResourceManager.GetString("EtiquetaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de Contrato.
        /// </summary>
        public static string EtiquetaEstadoContrato {
            get {
                return ResourceManager.GetString("EtiquetaEstadoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string EtiquetaHasta {
            get {
                return ResourceManager.GetString("EtiquetaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto Acumulado Fin.
        /// </summary>
        public static string EtiquetaMontoAcumuladoFin {
            get {
                return ResourceManager.GetString("EtiquetaMontoAcumuladoFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto Acumulado Inicio.
        /// </summary>
        public static string EtiquetaMontoAcumuladoInicio {
            get {
                return ResourceManager.GetString("EtiquetaMontoAcumuladoInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Contrato.
        /// </summary>
        public static string EtiquetaNumeroContrato {
            get {
                return ResourceManager.GetString("EtiquetaNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón Social Proveedor.
        /// </summary>
        public static string EtiquetaRazonSocial {
            get {
                return ResourceManager.GetString("EtiquetaRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUC Proveedor.
        /// </summary>
        public static string EtiquetaRucProveedor {
            get {
                return ResourceManager.GetString("EtiquetaRucProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        public static string EtiquetaTipoDocumento {
            get {
                return ResourceManager.GetString("EtiquetaTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Servicio.
        /// </summary>
        public static string EtiquetaTipoRequerimiento {
            get {
                return ResourceManager.GetString("EtiquetaTipoRequerimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Contrato.
        /// </summary>
        public static string EtiquetaTipoServicio {
            get {
                return ResourceManager.GetString("EtiquetaTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Listado de Contratos.
        /// </summary>
        public static string EtiquetaTitulo {
            get {
                return ResourceManager.GetString("EtiquetaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Operativa.
        /// </summary>
        public static string EtiquetaUnidadOperativa {
            get {
                return ResourceManager.GetString("EtiquetaUnidadOperativa", resourceCulture);
            }
        }
    }
}
