//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Presentacion.Recursos.Contractual {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReporteContratoPorFinalizarResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReporteContratoPorFinalizarResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Presentacion.Recursos.Contractual.ReporteContratoPorFinalizarResou" +
                            "rce", typeof(ReporteContratoPorFinalizarResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobados.
        /// </summary>
        public static string EtiquetaAprobados {
            get {
                return ResourceManager.GetString("EtiquetaAprobados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Contrato.
        /// </summary>
        public static string EtiquetaNumeroContrato {
            get {
                return ResourceManager.GetString("EtiquetaNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Contrato.
        /// </summary>
        public static string EtiquetaTipoContrato {
            get {
                return ResourceManager.GetString("EtiquetaTipoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Servicio.
        /// </summary>
        public static string EtiquetaTipoServicio {
            get {
                return ResourceManager.GetString("EtiquetaTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Contrato por Finalizar / Finalizado.
        /// </summary>
        public static string EtiquetaTitulo {
            get {
                return ResourceManager.GetString("EtiquetaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Estadio.
        /// </summary>
        public static string EtiquetaUltimoEstadio {
            get {
                return ResourceManager.GetString("EtiquetaUltimoEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Estadio / Aprobados.
        /// </summary>
        public static string EtiquetaUltimoEstadioAprobado {
            get {
                return ResourceManager.GetString("EtiquetaUltimoEstadioAprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Operativa.
        /// </summary>
        public static string EtiquetaUnidadOperativa {
            get {
                return ResourceManager.GetString("EtiquetaUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadio.
        /// </summary>
        public static string GridEstadio {
            get {
                return ResourceManager.GetString("GridEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Proveedor.
        /// </summary>
        public static string GridNombreProveedor {
            get {
                return ResourceManager.GetString("GridNombreProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Contrato / Número de Adenda.
        /// </summary>
        public static string GridNumeroContratoAdenda {
            get {
                return ResourceManager.GetString("GridNumeroContratoAdenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUC Proveedor.
        /// </summary>
        public static string GridRucProveedor {
            get {
                return ResourceManager.GetString("GridRucProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Estadio / Aprobados..
        /// </summary>
        public static string GridUltimoEstadioAprobado {
            get {
                return ResourceManager.GetString("GridUltimoEstadioAprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Operativa.
        /// </summary>
        public static string GridUnidadOperativa {
            get {
                return ResourceManager.GetString("GridUnidadOperativa", resourceCulture);
            }
        }
    }
}
