//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Presentacion.Recursos.Contractual {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReporteContratoCorporativoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReporteContratoCorporativoResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Presentacion.Recursos.Contractual.ReporteContratoCorporativoResour" +
                            "ce", typeof(ReporteContratoCorporativoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        public static string EtiquetaDesde {
            get {
                return ResourceManager.GetString("EtiquetaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Contrato.
        /// </summary>
        public static string EtiquetaEstadoContrato {
            get {
                return ResourceManager.GetString("EtiquetaEstadoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        public static string EtiquetaHasta {
            get {
                return ResourceManager.GetString("EtiquetaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Contrato.
        /// </summary>
        public static string EtiquetaNumeroContrato {
            get {
                return ResourceManager.GetString("EtiquetaNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón Social del Proveedor.
        /// </summary>
        public static string EtiquetaRazonSocial {
            get {
                return ResourceManager.GetString("EtiquetaRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUC del Proveedor.
        /// </summary>
        public static string EtiquetaRucProveedor {
            get {
                return ResourceManager.GetString("EtiquetaRucProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Documento.
        /// </summary>
        public static string EtiquetaTipoDocumento {
            get {
                return ResourceManager.GetString("EtiquetaTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Servicio.
        /// </summary>
        public static string EtiquetaTipoRequerimiento {
            get {
                return ResourceManager.GetString("EtiquetaTipoRequerimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Contrato.
        /// </summary>
        public static string EtiquetaTipoServicio {
            get {
                return ResourceManager.GetString("EtiquetaTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de Contratos Corporativos.
        /// </summary>
        public static string EtiquetaTitulo {
            get {
                return ResourceManager.GetString("EtiquetaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string EtiquetaUnidadOperativa {
            get {
                return ResourceManager.GetString("EtiquetaUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string GridAcciones {
            get {
                return ResourceManager.GetString("GridAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string GridDescripcion {
            get {
                return ResourceManager.GetString("GridDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Contrato.
        /// </summary>
        public static string GridEstadoContrato {
            get {
                return ResourceManager.GetString("GridEstadoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Creación.
        /// </summary>
        public static string GridFechaCreacion {
            get {
                return ResourceManager.GetString("GridFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Fin.
        /// </summary>
        public static string GridFechaFin {
            get {
                return ResourceManager.GetString("GridFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        public static string GridFechaInicio {
            get {
                return ResourceManager.GetString("GridFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Adenda.
        /// </summary>
        public static string GridNumeroAdenda {
            get {
                return ResourceManager.GetString("GridNumeroAdenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Contrato.
        /// </summary>
        public static string GridNumeroContrato {
            get {
                return ResourceManager.GetString("GridNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUC/Proveedor.
        /// </summary>
        public static string GridProveedor {
            get {
                return ResourceManager.GetString("GridProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Contrato.
        /// </summary>
        public static string GridTipoContrato {
            get {
                return ResourceManager.GetString("GridTipoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Documento.
        /// </summary>
        public static string GridTipoDocumento {
            get {
                return ResourceManager.GetString("GridTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Servicio.
        /// </summary>
        public static string GridTipoServicio {
            get {
                return ResourceManager.GetString("GridTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string GridUnidadOperativa {
            get {
                return ResourceManager.GetString("GridUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario de Creación.
        /// </summary>
        public static string GridUsuarioCreacion {
            get {
                return ResourceManager.GetString("GridUsuarioCreacion", resourceCulture);
            }
        }
    }
}
