//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Presentacion.Recursos.Contractual {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SolicitudModificacionContratoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SolicitudModificacionContratoResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Presentacion.Recursos.Contractual.SolicitudModificacionContratoRes" +
                            "ource", typeof(SolicitudModificacionContratoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EA.
        /// </summary>
        public static string CodigoEdicionAprobada {
            get {
                return ResourceManager.GetString("CodigoEdicionAprobada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ER.
        /// </summary>
        public static string CodigoEdicionRechazada {
            get {
                return ResourceManager.GetString("CodigoEdicionRechazada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SA.
        /// </summary>
        public static string CodigoSolicitudAutorizada {
            get {
                return ResourceManager.GetString("CodigoSolicitudAutorizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SD.
        /// </summary>
        public static string CodigoSolicitudDenegada {
            get {
                return ResourceManager.GetString("CodigoSolicitudDenegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario de Respuesta.
        /// </summary>
        public static string EtiquetaComentarioRespuesta {
            get {
                return ResourceManager.GetString("EtiquetaComentarioRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato Modificado.
        /// </summary>
        public static string EtiquetaContratoModificado {
            get {
                return ResourceManager.GetString("EtiquetaContratoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de la Modificación Solicitada.
        /// </summary>
        public static string EtiquetaDescripcionModificacionSolicitada {
            get {
                return ResourceManager.GetString("EtiquetaDescripcionModificacionSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Contrato.
        /// </summary>
        public static string EtiquetaFormularioContrato {
            get {
                return ResourceManager.GetString("EtiquetaFormularioContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Contrato.
        /// </summary>
        public static string EtiquetaNumeroContrato {
            get {
                return ResourceManager.GetString("EtiquetaNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato Original.
        /// </summary>
        public static string EtiquetaOriginal {
            get {
                return ResourceManager.GetString("EtiquetaOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string EtiquetaProveedor {
            get {
                return ResourceManager.GetString("EtiquetaProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Modificación de Contrato.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string EtiquetaUnidadOperativa {
            get {
                return ResourceManager.GetString("EtiquetaUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista Previa.
        /// </summary>
        public static string EtiquetaVistaPrevia {
            get {
                return ResourceManager.GetString("EtiquetaVistaPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string GridEstado {
            get {
                return ResourceManager.GetString("GridEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Ingreso.
        /// </summary>
        public static string GridFechaIngreso {
            get {
                return ResourceManager.GetString("GridFechaIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Contrato.
        /// </summary>
        public static string GridNumeroContrato {
            get {
                return ResourceManager.GetString("GridNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string GridProveedor {
            get {
                return ResourceManager.GetString("GridProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string GridTipo {
            get {
                return ResourceManager.GetString("GridTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string GridUnidadOperativa {
            get {
                return ResourceManager.GetString("GridUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Creación.
        /// </summary>
        public static string GridUsuarioCreacion {
            get {
                return ResourceManager.GetString("GridUsuarioCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar la respuesta a la modificación solicitada..
        /// </summary>
        public static string MsjValidaRespuestaSolicitud {
            get {
                return ResourceManager.GetString("MsjValidaRespuestaSolicitud", resourceCulture);
            }
        }
    }
}
