//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Presentacion.Recursos.Contractual {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SolicitudRevisionContratoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SolicitudRevisionContratoResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Presentacion.Recursos.Contractual.SolicitudRevisionContratoResourc" +
                            "e", typeof(SolicitudRevisionContratoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RA.
        /// </summary>
        public static string CodigoRevisionAprobada {
            get {
                return ResourceManager.GetString("CodigoRevisionAprobada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RR.
        /// </summary>
        public static string CodigoRevisionRechazada {
            get {
                return ResourceManager.GetString("CodigoRevisionRechazada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato Modificado.
        /// </summary>
        public static string EtiquetaContratoModificado {
            get {
                return ResourceManager.GetString("EtiquetaContratoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de la Modificación Solicitada.
        /// </summary>
        public static string EtiquetaDescripcionModificacionSolicitada {
            get {
                return ResourceManager.GetString("EtiquetaDescripcionModificacionSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Contrato.
        /// </summary>
        public static string EtiquetaFormularioContrato {
            get {
                return ResourceManager.GetString("EtiquetaFormularioContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Contrato.
        /// </summary>
        public static string EtiquetaNumeroContrato {
            get {
                return ResourceManager.GetString("EtiquetaNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string EtiquetaProveedor {
            get {
                return ResourceManager.GetString("EtiquetaProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Revisión de Contrato.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el motivo por el que desea rechazar la revisión del contrato.
        /// </summary>
        public static string EtiquetaTituloRechazo {
            get {
                return ResourceManager.GetString("EtiquetaTituloRechazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string EtiquetaUnidadOperativa {
            get {
                return ResourceManager.GetString("EtiquetaUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string GridEstado {
            get {
                return ResourceManager.GetString("GridEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Ingreso.
        /// </summary>
        public static string GridFechaIngreso {
            get {
                return ResourceManager.GetString("GridFechaIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Contrato.
        /// </summary>
        public static string GridNumeroContrato {
            get {
                return ResourceManager.GetString("GridNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string GridProveedor {
            get {
                return ResourceManager.GetString("GridProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string GridTipo {
            get {
                return ResourceManager.GetString("GridTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string GridUnidadOperativa {
            get {
                return ResourceManager.GetString("GridUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Creación.
        /// </summary>
        public static string GridUsuarioCreacion {
            get {
                return ResourceManager.GetString("GridUsuarioCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar un motivo de rechazo de la revisión del contrato..
        /// </summary>
        public static string MensajeMotivoRechazo {
            get {
                return ResourceManager.GetString("MensajeMotivoRechazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de Rechazar la revisión de este contrato?.
        /// </summary>
        public static string PreguntaRechazo {
            get {
                return ResourceManager.GetString("PreguntaRechazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar revisión del contrato.
        /// </summary>
        public static string RechazoRevision {
            get {
                return ResourceManager.GetString("RechazoRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo de Rechazo de Revision.
        /// </summary>
        public static string TituloMotivoRechazo {
            get {
                return ResourceManager.GetString("TituloMotivoRechazo", resourceCulture);
            }
        }
    }
}
