//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Politicas.Presentacion.Recursos.Mensajes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajeResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.Politicas.Presentacion.Recursos.Mensajes.MensajeResource", typeof(MensajeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario Válido.
        /// </summary>
        public static string ComentarioValido {
            get {
                return ResourceManager.GetString("ComentarioValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario Válido.
        /// </summary>
        public static string ComentarioValido1 {
            get {
                return ResourceManager.GetString("ComentarioValido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de aprobar las modificaciones realizadas?.
        /// </summary>
        public static string ConfirmacionAprobar {
            get {
                return ResourceManager.GetString("ConfirmacionAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de autorizar la solicitud de modificación?.
        /// </summary>
        public static string ConfirmacionAutorizar {
            get {
                return ResourceManager.GetString("ConfirmacionAutorizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de denegar la solicitud de modificación?.
        /// </summary>
        public static string ConfirmacionDenegar {
            get {
                return ResourceManager.GetString("ConfirmacionDenegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar el registro?.
        /// </summary>
        public static string ConfirmacionEliminacion {
            get {
                return ResourceManager.GetString("ConfirmacionEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar el registro?.
        /// </summary>
        public static string ConfirmacionEliminacion1 {
            get {
                return ResourceManager.GetString("ConfirmacionEliminacion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar los registros seleccionados?.
        /// </summary>
        public static string ConfirmacionEliminacionVarios {
            get {
                return ResourceManager.GetString("ConfirmacionEliminacionVarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de grabar los cambios solicitados?.
        /// </summary>
        public static string ConfirmacionGuardar {
            get {
                return ResourceManager.GetString("ConfirmacionGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de grabar los cambios solicitados?.
        /// </summary>
        public static string ConfirmacionGuardar1 {
            get {
                return ResourceManager.GetString("ConfirmacionGuardar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de añadir al usuario seleccionado?.
        /// </summary>
        public static string ConfirmacionGuardarUsuario {
            get {
                return ResourceManager.GetString("ConfirmacionGuardarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de rechazar la solicitud de modificación?.
        /// </summary>
        public static string ConfirmacionRechazar {
            get {
                return ResourceManager.GetString("ConfirmacionRechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar datos para realizar la búsqueda..
        /// </summary>
        public static string DebeIngresarDato {
            get {
                return ResourceManager.GetString("DebeIngresarDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una fecha..
        /// </summary>
        public static string DebeSeleccionarFecha {
            get {
                return ResourceManager.GetString("DebeSeleccionarFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una fecha..
        /// </summary>
        public static string DebeSeleccionarFecha1 {
            get {
                return ResourceManager.GetString("DebeSeleccionarFecha1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un registro..
        /// </summary>
        public static string DebeSeleccionarRegistro {
            get {
                return ResourceManager.GetString("DebeSeleccionarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un registro..
        /// </summary>
        public static string DebeSeleccionarRegistro1 {
            get {
                return ResourceManager.GetString("DebeSeleccionarRegistro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un archivo..
        /// </summary>
        public static string DebeSeleccionarUnArchivo {
            get {
                return ResourceManager.GetString("DebeSeleccionarUnArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar sólo un registro..
        /// </summary>
        public static string DebeSeleccionarUnRegistro {
            get {
                return ResourceManager.GetString("DebeSeleccionarUnRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar sólo un registro..
        /// </summary>
        public static string DebeSeleccionarUnRegistro1 {
            get {
                return ResourceManager.GetString("DebeSeleccionarUnRegistro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al grabar el registro..
        /// </summary>
        public static string ErroralGrabar {
            get {
                return ResourceManager.GetString("ErroralGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al grabar el registro..
        /// </summary>
        public static string ErrorAlGrabar1 {
            get {
                return ResourceManager.GetString("ErrorAlGrabar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View model no definido..
        /// </summary>
        public static string ErrorCargarViewModel {
            get {
                return ResourceManager.GetString("ErrorCargarViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View model no definido..
        /// </summary>
        public static string ErrorCargarViewModel1 {
            get {
                return ResourceManager.GetString("ErrorCargarViewModel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado. Inténtelo nuevamente.
        /// </summary>
        public static string EtiquetaErrorRegistro {
            get {
                return ResourceManager.GetString("EtiquetaErrorRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado. Inténtelo nuevamente.
        /// </summary>
        public static string EtiquetaErrorRegistro1 {
            get {
                return ResourceManager.GetString("EtiquetaErrorRegistro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ejecuto ningun proceso..
        /// </summary>
        public static string EtiquetaNoEjecutoNingunProceso {
            get {
                return ResourceManager.GetString("EtiquetaNoEjecutoNingunProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ejecuto ningun proceso..
        /// </summary>
        public static string EtiquetaNoEjecutoNingunProceso1 {
            get {
                return ResourceManager.GetString("EtiquetaNoEjecutoNingunProceso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        public static string EtiquetaTituloAdvertencia {
            get {
                return ResourceManager.GetString("EtiquetaTituloAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        public static string EtiquetaTituloAdvertencia1 {
            get {
                return ResourceManager.GetString("EtiquetaTituloAdvertencia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string EtiquetaTituloError {
            get {
                return ResourceManager.GetString("EtiquetaTituloError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Demanda ya existe.
        /// </summary>
        public static string ExistenciaCodigoDemanda {
            get {
                return ResourceManager.GetString("ExistenciaCodigoDemanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro seleccionado ya está registrado.
        /// </summary>
        public static string ExistenciaRegistro {
            get {
                return ResourceManager.GetString("ExistenciaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de depósito distinto..
        /// </summary>
        public static string FechaRegistroDistinta {
            get {
                return ResourceManager.GetString("FechaRegistroDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un formato de archivo válido..
        /// </summary>
        public static string FormatoArchivoValido {
            get {
                return ResourceManager.GetString("FormatoArchivoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe de pago distinto..
        /// </summary>
        public static string ImportePagoDistinta {
            get {
                return ResourceManager.GetString("ImportePagoDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar al menos un filtro de búsqueda..
        /// </summary>
        public static string InformacionIngresarFiltro {
            get {
                return ResourceManager.GetString("InformacionIngresarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar al menos un filtro de búsqueda..
        /// </summary>
        public static string InformacionIngresarFiltro1 {
            get {
                return ResourceManager.GetString("InformacionIngresarFiltro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información mostrada corresponde a la.
        /// </summary>
        public static string InformacionPreFiltro {
            get {
                return ResourceManager.GetString("InformacionPreFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información mostrada corresponde a la.
        /// </summary>
        public static string InformacionPreFiltro1 {
            get {
                return ResourceManager.GetString("InformacionPreFiltro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud no ha podido ser procesada. Comuníquese con el Administrador del Sistema..
        /// </summary>
        public static string MensajeException {
            get {
                return ResourceManager.GetString("MensajeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud no ha podido ser procesada. Comuníquese con el Administrador del Sistema..
        /// </summary>
        public static string MensajeException1 {
            get {
                return ResourceManager.GetString("MensajeException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe Ingresar valores mayores a 0.
        /// </summary>
        public static string MensajeValidacionMayores {
            get {
                return ResourceManager.GetString("MensajeValidacionMayores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar los registros?.
        /// </summary>
        public static string MsgEliminacionList {
            get {
                return ResourceManager.GetString("MsgEliminacionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar los registros?.
        /// </summary>
        public static string MsgEliminacionList1 {
            get {
                return ResourceManager.GetString("MsgEliminacionList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un archivo, verifique..
        /// </summary>
        public static string MsjValidaEligeArchivo {
            get {
                return ResourceManager.GetString("MsjValidaEligeArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo elegido no tiene la extensión permitida, verifique..
        /// </summary>
        public static string MsjValidaExtensionArchivo {
            get {
                return ResourceManager.GetString("MsjValidaExtensionArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los registros seleccionados no coinciden:.
        /// </summary>
        public static string RegistrosNoCoinciden {
            get {
                return ResourceManager.GetString("RegistrosNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los registros seleccionados no coinciden:.
        /// </summary>
        public static string RegistrosNoCoinciden1 {
            get {
                return ResourceManager.GetString("RegistrosNoCoinciden1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se anuló registro con éxito..
        /// </summary>
        public static string SeAnuloRegistro {
            get {
                return ResourceManager.GetString("SeAnuloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se anuló registro con éxito..
        /// </summary>
        public static string SeAnuloRegistro1 {
            get {
                return ResourceManager.GetString("SeAnuloRegistro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminación ejecutada con éxito..
        /// </summary>
        public static string SeEliminoInformacionExito {
            get {
                return ResourceManager.GetString("SeEliminoInformacionExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminación ejecutada con éxito..
        /// </summary>
        public static string SeEliminoInformacionExito1 {
            get {
                return ResourceManager.GetString("SeEliminoInformacionExito1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminó el(los) registro(s) con éxito..
        /// </summary>
        public static string SeEliminoRegistro {
            get {
                return ResourceManager.GetString("SeEliminoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardó la información con éxito..
        /// </summary>
        public static string SeGuardoInformacionExito {
            get {
                return ResourceManager.GetString("SeGuardoInformacionExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardó la información con éxito..
        /// </summary>
        public static string SeGuardoInformacionExito1 {
            get {
                return ResourceManager.GetString("SeGuardoInformacionExito1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardó la información con éxito..
        /// </summary>
        public static string SeGuardoInformacionExito2 {
            get {
                return ResourceManager.GetString("SeGuardoInformacionExito2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un registro para eliminar..
        /// </summary>
        public static string SeleccionarRegistroEliminar {
            get {
                return ResourceManager.GetString("SeleccionarRegistroEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un registro para eliminar..
        /// </summary>
        public static string SeleccionarRegistroEliminar1 {
            get {
                return ResourceManager.GetString("SeleccionarRegistroEliminar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos un parámetro de filtro correcto.
        /// </summary>
        public static string SeleccioneFiltro {
            get {
                return ResourceManager.GetString("SeleccioneFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos un parámetro de filtro correcto.
        /// </summary>
        public static string SeleccioneFiltro1 {
            get {
                return ResourceManager.GetString("SeleccioneFiltro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar :.
        /// </summary>
        public static string SumaryValidacion {
            get {
                return ResourceManager.GetString("SumaryValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe Seleccionar al Menos Uno de los Siguientes Campos.
        /// </summary>
        public static string ValidarCamposAlMenosUno {
            get {
                return ResourceManager.GetString("ValidarCamposAlMenosUno", resourceCulture);
            }
        }
    }
}
