//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Presentacion.Recursos.Contractual {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArchivoAdjuntoContratoResolucionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArchivoAdjuntoContratoResolucionResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Presentacion.Recursos.Contractual.ArchivoAdjuntoContratoResolucion" +
                            "Resource", typeof(ArchivoAdjuntoContratoResolucionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar documento adjunto.
        /// </summary>
        public static string EtiquetaDlgTituloEliminar {
            get {
                return ResourceManager.GetString("EtiquetaDlgTituloEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Resolución.
        /// </summary>
        public static string EtiquetaFechaResolucion {
            get {
                return ResourceManager.GetString("EtiquetaFechaResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Archivo.
        /// </summary>
        public static string EtiquetaNombreArchivo {
            get {
                return ResourceManager.GetString("EtiquetaNombreArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizado por.
        /// </summary>
        public static string EtiquetaUsuarioResponsable {
            get {
                return ResourceManager.GetString("EtiquetaUsuarioResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden eliminar documentos adjuntos del contrato.
        /// </summary>
        public static string EtiquetaValidarEliminacionAdjunto {
            get {
                return ResourceManager.GetString("EtiquetaValidarEliminacionAdjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden adjuntar documentos al contrato.
        /// </summary>
        public static string EtiquetaValidarRegistroAdjunto {
            get {
                return ResourceManager.GetString("EtiquetaValidarRegistroAdjunto", resourceCulture);
            }
        }
    }
}
