//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Presentacion.Recursos.Contractual {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BandejaContratoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BandejaContratoResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Presentacion.Recursos.Contractual.BandejaContratoResource", typeof(BandejaContratoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultas.
        /// </summary>
        public static string BtnConsultas {
            get {
                return ResourceManager.GetString("BtnConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A.
        /// </summary>
        public static string CodigoRptaObservacionAplica {
            get {
                return ResourceManager.GetString("CodigoRptaObservacionAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N.
        /// </summary>
        public static string CodigoRptaObservacionNoAplica {
            get {
                return ResourceManager.GetString("CodigoRptaObservacionNoAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta.
        /// </summary>
        public static string EtiquetaConsulta {
            get {
                return ResourceManager.GetString("EtiquetaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        public static string EtiquetaContrato {
            get {
                return ResourceManager.GetString("EtiquetaContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destinatario.
        /// </summary>
        public static string EtiquetaDestinatario {
            get {
                return ResourceManager.GetString("EtiquetaDestinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar a:.
        /// </summary>
        public static string EtiquetaEnviarA {
            get {
                return ResourceManager.GetString("EtiquetaEnviarA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Creación.
        /// </summary>
        public static string EtiquetaFechaCreacion {
            get {
                return ResourceManager.GetString("EtiquetaFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Consulta.
        /// </summary>
        public static string EtiquetaFormularioNuevaConsulta {
            get {
                return ResourceManager.GetString("EtiquetaFormularioNuevaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responder Consulta.
        /// </summary>
        public static string EtiquetaFormularioResponderConsulta {
            get {
                return ResourceManager.GetString("EtiquetaFormularioResponderConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responder Observación.
        /// </summary>
        public static string EtiquetaFormularioResponderObservacion {
            get {
                return ResourceManager.GetString("EtiquetaFormularioResponderObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Información.
        /// </summary>
        public static string EtiquetaFormularioVerConsulta {
            get {
                return ResourceManager.GetString("EtiquetaFormularioVerConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Contrato.
        /// </summary>
        public static string EtiquetaNumeroContrato {
            get {
                return ResourceManager.GetString("EtiquetaNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación.
        /// </summary>
        public static string EtiquetaObservacion {
            get {
                return ResourceManager.GetString("EtiquetaObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Párrafo relacionado.
        /// </summary>
        public static string EtiquetaParrafoRelacionado {
            get {
                return ResourceManager.GetString("EtiquetaParrafoRelacionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string EtiquetaProveedor {
            get {
                return ResourceManager.GetString("EtiquetaProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reemplazar Contrato.
        /// </summary>
        public static string EtiquetaReemplazarContrato {
            get {
                return ResourceManager.GetString("EtiquetaReemplazarContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remitente.
        /// </summary>
        public static string EtiquetaRemitente {
            get {
                return ResourceManager.GetString("EtiquetaRemitente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta.
        /// </summary>
        public static string EtiquetaRespuesta {
            get {
                return ResourceManager.GetString("EtiquetaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a R.U.C..
        /// </summary>
        public static string EtiquetaRUCProveedor {
            get {
                return ResourceManager.GetString("EtiquetaRUCProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string EtiquetaTipoConsulta {
            get {
                return ResourceManager.GetString("EtiquetaTipoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Servicio.
        /// </summary>
        public static string EtiquetaTipoRequerimiento {
            get {
                return ResourceManager.GetString("EtiquetaTipoRequerimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Contrato.
        /// </summary>
        public static string EtiquetaTipoServicio {
            get {
                return ResourceManager.GetString("EtiquetaTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultas.
        /// </summary>
        public static string EtiquetaTituloConsultas {
            get {
                return ResourceManager.GetString("EtiquetaTituloConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Observación.
        /// </summary>
        public static string EtiquetaTituloFormulario {
            get {
                return ResourceManager.GetString("EtiquetaTituloFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string EtiquetaTituloObservaciones {
            get {
                return ResourceManager.GetString("EtiquetaTituloObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bandeja de Contratos.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Organizacional.
        /// </summary>
        public static string EtiquetaUnidadOrganizacional {
            get {
                return ResourceManager.GetString("EtiquetaUnidadOrganizacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta.
        /// </summary>
        public static string GridConsulta {
            get {
                return ResourceManager.GetString("GridConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultado Por .
        /// </summary>
        public static string GridConsultadoPor {
            get {
                return ResourceManager.GetString("GridConsultadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato Anterior.
        /// </summary>
        public static string GridContratoAnterior {
            get {
                return ResourceManager.GetString("GridContratoAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato Reemplazante.
        /// </summary>
        public static string GridContratoReemplazante {
            get {
                return ResourceManager.GetString("GridContratoReemplazante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string GridDescripcionContrato {
            get {
                return ResourceManager.GetString("GridDescripcionContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de aprobar el estadio actual del contrato?.
        /// </summary>
        public static string GridDescripcionMensajeAprobar {
            get {
                return ResourceManager.GetString("GridDescripcionMensajeAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días en Pendiente.
        /// </summary>
        public static string GridDiasPendiente {
            get {
                return ResourceManager.GetString("GridDiasPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirigido A.
        /// </summary>
        public static string GridDirigidoA {
            get {
                return ResourceManager.GetString("GridDirigidoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadio.
        /// </summary>
        public static string GridEstadio {
            get {
                return ResourceManager.GetString("GridEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Consulta.
        /// </summary>
        public static string GridFechaConsulta {
            get {
                return ResourceManager.GetString("GridFechaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Creación.
        /// </summary>
        public static string GridFechaCreacion {
            get {
                return ResourceManager.GetString("GridFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Notificación.
        /// </summary>
        public static string GridFechaNotificacion {
            get {
                return ResourceManager.GetString("GridFechaNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Observación.
        /// </summary>
        public static string GridFechaObservacion {
            get {
                return ResourceManager.GetString("GridFechaObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Respuesta.
        /// </summary>
        public static string GridFechaRespuesta {
            get {
                return ResourceManager.GetString("GridFechaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Contrato.
        /// </summary>
        public static string GridNumeroContrato {
            get {
                return ResourceManager.GetString("GridNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación.
        /// </summary>
        public static string GridObservacion {
            get {
                return ResourceManager.GetString("GridObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observado Por.
        /// </summary>
        public static string GridObservadoPor {
            get {
                return ResourceManager.GetString("GridObservadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string GridProveedor {
            get {
                return ResourceManager.GetString("GridProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respondido Por.
        /// </summary>
        public static string GridRespondidoPor {
            get {
                return ResourceManager.GetString("GridRespondidoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta.
        /// </summary>
        public static string GridRespuesta {
            get {
                return ResourceManager.GetString("GridRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Servicio.
        /// </summary>
        public static string GridTipoRequerimiento {
            get {
                return ResourceManager.GetString("GridTipoRequerimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Respuesta.
        /// </summary>
        public static string GridTipoRespuesta {
            get {
                return ResourceManager.GetString("GridTipoRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Contrato.
        /// </summary>
        public static string GridTipoServicio {
            get {
                return ResourceManager.GetString("GridTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Aprobación.
        /// </summary>
        public static string GridTituloMensajeAprobar {
            get {
                return ResourceManager.GetString("GridTituloMensajeAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Organizacional.
        /// </summary>
        public static string GridUnidadOrganizacional {
            get {
                return ResourceManager.GetString("GridUnidadOrganizacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario de Creación.
        /// </summary>
        public static string GridUsuarioCreacion {
            get {
                return ResourceManager.GetString("GridUsuarioCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una Evidencia a donde enviar la información..
        /// </summary>
        public static string MsjValidarNoEvidenciaObservacion {
            get {
                return ResourceManager.GetString("MsjValidarNoEvidenciaObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos una persona  a la cual enviar con copia la notificación..
        /// </summary>
        public static string MsjValidarObservacionConCopia {
            get {
                return ResourceManager.GetString("MsjValidarObservacionConCopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar la respuesta para grabar, verifique..
        /// </summary>
        public static string MsjValidarRespuesta {
            get {
                return ResourceManager.GetString("MsjValidarRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar la Consulta para poder grabar..
        /// </summary>
        public static string MsjValidarTextoConsulta {
            get {
                return ResourceManager.GetString("MsjValidarTextoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar la Observación para poder grabar..
        /// </summary>
        public static string MsjValidarTextoObservacion {
            get {
                return ResourceManager.GetString("MsjValidarTextoObservacion", resourceCulture);
            }
        }
    }
}
