//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.SGC.Presentacion.Recursos.Contractual {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListadoRequerimientoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListadoRequerimientoResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Stracon.SGC.Presentacion.Recursos.Contractual.ListadoRequerimientoResource", typeof(ListadoRequerimientoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 99.
        /// </summary>
        public static string CodigoDocAjuntoOtros {
            get {
                return ResourceManager.GetString("CodigoDocAjuntoOtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bandeja.
        /// </summary>
        public static string EtiquetaBandeja {
            get {
                return ResourceManager.GetString("EtiquetaBandeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Requerimiento.
        /// </summary>
        public static string EtiquetaBotonGenerarContrato {
            get {
                return ResourceManager.GetString("EtiquetaBotonGenerarContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenido del Requerimiento.
        /// </summary>
        public static string EtiquetaContenidoContrato {
            get {
                return ResourceManager.GetString("EtiquetaContenidoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato Corporativo.
        /// </summary>
        public static string EtiquetaContratoCorporativo {
            get {
                return ResourceManager.GetString("EtiquetaContratoCorporativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato Principal.
        /// </summary>
        public static string EtiquetaContratoPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaContratoPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string EtiquetaCPGridDescripCon {
            get {
                return ResourceManager.GetString("EtiquetaCPGridDescripCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Contrato.
        /// </summary>
        public static string EtiquetaCPGridNumeroCon {
            get {
                return ResourceManager.GetString("EtiquetaCPGridNumeroCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string EtiquetaCPGridProveedor {
            get {
                return ResourceManager.GetString("EtiquetaCPGridProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar contrato principal.
        /// </summary>
        public static string EtiquetaCPTitulo {
            get {
                return ResourceManager.GetString("EtiquetaCPTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de la Modificación Solicitada.
        /// </summary>
        public static string EtiquetaDescripcionModificacionSolicitada {
            get {
                return ResourceManager.GetString("EtiquetaDescripcionModificacionSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Otros.
        /// </summary>
        public static string EtiquetaDesOtros {
            get {
                return ResourceManager.GetString("EtiquetaDesOtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Contrato.
        /// </summary>
        public static string EtiquetaDlgTituloEliminar {
            get {
                return ResourceManager.GetString("EtiquetaDlgTituloEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento Adjunto.
        /// </summary>
        public static string EtiquetaDocumentoAdjunto {
            get {
                return ResourceManager.GetString("EtiquetaDocumentoAdjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadio.
        /// </summary>
        public static string EtiquetaEstadio {
            get {
                return ResourceManager.GetString("EtiquetaEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Contrato.
        /// </summary>
        public static string EtiquetaEstadoContrato {
            get {
                return ResourceManager.GetString("EtiquetaEstadoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Edición.
        /// </summary>
        public static string EtiquetaEstadoEdicion {
            get {
                return ResourceManager.GetString("EtiquetaEstadoEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Fin.
        /// </summary>
        public static string EtiquetaFechaFinVigencia {
            get {
                return ResourceManager.GetString("EtiquetaFechaFinVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio.
        /// </summary>
        public static string EtiquetaFechaInicioVigencia {
            get {
                return ResourceManager.GetString("EtiquetaFechaInicioVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Resolución.
        /// </summary>
        public static string EtiquetaFechaResolucion {
            get {
                return ResourceManager.GetString("EtiquetaFechaResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar Aprobación.
        /// </summary>
        public static string EtiquetaFinalizarAprobacion {
            get {
                return ResourceManager.GetString("EtiquetaFinalizarAprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar Contrato.
        /// </summary>
        public static string EtiquetaFinalizarContrato {
            get {
                return ResourceManager.GetString("EtiquetaFinalizarContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Requerimiento.
        /// </summary>
        public static string EtiquetaFormularioContrato {
            get {
                return ResourceManager.GetString("EtiquetaFormularioContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Contrato Párrafo.
        /// </summary>
        public static string EtiquetaFormularioContratoParrafo {
            get {
                return ResourceManager.GetString("EtiquetaFormularioContratoParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipos a Contratar.
        /// </summary>
        public static string EtiquetaFormularioContratoParrafoBien {
            get {
                return ResourceManager.GetString("EtiquetaFormularioContratoParrafoBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firmantes.
        /// </summary>
        public static string EtiquetaFormularioContratoParrafoFirmante {
            get {
                return ResourceManager.GetString("EtiquetaFormularioContratoParrafoFirmante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenido de Tabla.
        /// </summary>
        public static string EtiquetaFormularioContratoParrafoTabla {
            get {
                return ResourceManager.GetString("EtiquetaFormularioContratoParrafoTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Vista Previa del Contrato.
        /// </summary>
        public static string EtiquetaFormularioContratoVistaPrevia {
            get {
                return ResourceManager.GetString("EtiquetaFormularioContratoVistaPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Listado de Contrato.
        /// </summary>
        public static string EtiquetaFormularioListadoContrato {
            get {
                return ResourceManager.GetString("EtiquetaFormularioListadoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El monto acumulado del contrato con sus adendas supera los {0}{1}. Esta adenda pasará por un flujo mayor de aprobaciones..
        /// </summary>
        public static string EtiquetaInformacionMontoAcumulado {
            get {
                return ResourceManager.GetString("EtiquetaInformacionMontoAcumulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modalidad de Contratación.
        /// </summary>
        public static string EtiquetaModalidadCon {
            get {
                return ResourceManager.GetString("EtiquetaModalidadCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moneda.
        /// </summary>
        public static string EtiquetaMoneda {
            get {
                return ResourceManager.GetString("EtiquetaMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto del Requerimiento.
        /// </summary>
        public static string EtiquetaMontoContrato {
            get {
                return ResourceManager.GetString("EtiquetaMontoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar un Monto de Contrato Mayor a Cero (0).
        /// </summary>
        public static string EtiquetaMontoContratoMayorCero {
            get {
                return ResourceManager.GetString("EtiquetaMontoContratoMayorCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string EtiquetaNo {
            get {
                return ResourceManager.GetString("EtiquetaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Proveedor.
        /// </summary>
        public static string EtiquetaNombreProveedor {
            get {
                return ResourceManager.GetString("EtiquetaNombreProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de Adenda.
        /// </summary>
        public static string EtiquetaNumeroAdenda {
            get {
                return ResourceManager.GetString("EtiquetaNumeroAdenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número Requerimiento.
        /// </summary>
        public static string EtiquetaNumeroContrato {
            get {
                return ResourceManager.GetString("EtiquetaNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Párrafo.
        /// </summary>
        public static string EtiquetaParrafo {
            get {
                return ResourceManager.GetString("EtiquetaParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string EtiquetaProveedor {
            get {
                return ResourceManager.GetString("EtiquetaProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string EtiquetaRegistroTabla {
            get {
                return ResourceManager.GetString("EtiquetaRegistroTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requerido por.
        /// </summary>
        public static string EtiquetaRequerido {
            get {
                return ResourceManager.GetString("EtiquetaRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta del Autorizador.
        /// </summary>
        public static string EtiquetaRespuestaAutorizador {
            get {
                return ResourceManager.GetString("EtiquetaRespuestaAutorizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUC de Proveedor.
        /// </summary>
        public static string EtiquetaRucProveedor {
            get {
                return ResourceManager.GetString("EtiquetaRucProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí.
        /// </summary>
        public static string EtiquetaSi {
            get {
                return ResourceManager.GetString("EtiquetaSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Documento.
        /// </summary>
        public static string EtiquetaTipoDocumento {
            get {
                return ResourceManager.GetString("EtiquetaTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Moneda.
        /// </summary>
        public static string EtiquetaTipoMoneda {
            get {
                return ResourceManager.GetString("EtiquetaTipoMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Servicio.
        /// </summary>
        public static string EtiquetaTipoRequerimiento {
            get {
                return ResourceManager.GetString("EtiquetaTipoRequerimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Contrato.
        /// </summary>
        public static string EtiquetaTipoServicio {
            get {
                return ResourceManager.GetString("EtiquetaTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Requerimientos.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        public static string EtiquetaTodos {
            get {
                return ResourceManager.GetString("EtiquetaTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string EtiquetaUnidadOperativa {
            get {
                return ResourceManager.GetString("EtiquetaUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de contrato ya existe!.
        /// </summary>
        public static string EtiquetaValidacionNumeroContrato {
            get {
                return ResourceManager.GetString("EtiquetaValidacionNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha de Fin de Vigencia no puede ser menor a la Fecha de Inicio de Vigencia..
        /// </summary>
        public static string EtiquetaValidarRangoFechas {
            get {
                return ResourceManager.GetString("EtiquetaValidarRangoFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variables.
        /// </summary>
        public static string EtiquetaVariables {
            get {
                return ResourceManager.GetString("EtiquetaVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Variable de tipo Tabla no tiene columnas, primero regístrelas..
        /// </summary>
        public static string EtiquetaVariableTablaSinColumnas {
            get {
                return ResourceManager.GetString("EtiquetaVariableTablaSinColumnas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista Previa.
        /// </summary>
        public static string EtiquetaVistaPrevia {
            get {
                return ResourceManager.GetString("EtiquetaVistaPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Adicionales.
        /// </summary>
        public static string GridDatosAdicionales {
            get {
                return ResourceManager.GetString("GridDatosAdicionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string GridDescripcion {
            get {
                return ResourceManager.GetString("GridDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días para Vencimiento.
        /// </summary>
        public static string GridDiasVencimiento {
            get {
                return ResourceManager.GetString("GridDiasVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadio.
        /// </summary>
        public static string GridEstadioActual {
            get {
                return ResourceManager.GetString("GridEstadioActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de&lt;/br&gt;Contrato.
        /// </summary>
        public static string GridEstadoContrato {
            get {
                return ResourceManager.GetString("GridEstadoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de&lt;/br&gt;Edición.
        /// </summary>
        public static string GridEstadoEdicion {
            get {
                return ResourceManager.GetString("GridEstadoEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Creación.
        /// </summary>
        public static string GridFechaCreacion {
            get {
                return ResourceManager.GetString("GridFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha&lt;/br&gt;Fin.
        /// </summary>
        public static string GridFechaFin {
            get {
                return ResourceManager.GetString("GridFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha&lt;/br&gt;Inicio.
        /// </summary>
        public static string GridFechaInicio {
            get {
                return ResourceManager.GetString("GridFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha&lt;/br&gt;Resolución.
        /// </summary>
        public static string GridFechaResolucion {
            get {
                return ResourceManager.GetString("GridFechaResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Acumulado.
        /// </summary>
        public static string GridMontoAcumulado {
            get {
                return ResourceManager.GetString("GridMontoAcumulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Requerimiento.
        /// </summary>
        public static string GridMontoContrato {
            get {
                return ResourceManager.GetString("GridMontoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string GridNombre {
            get {
                return ResourceManager.GetString("GridNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En Bandeja De.
        /// </summary>
        public static string GridNombreResponsable {
            get {
                return ResourceManager.GetString("GridNombreResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa.
        /// </summary>
        public static string GridNombreUnidadOperativa {
            get {
                return ResourceManager.GetString("GridNombreUnidadOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Adenda.
        /// </summary>
        public static string GridNumeroAdenda {
            get {
                return ResourceManager.GetString("GridNumeroAdenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Requerimiento.
        /// </summary>
        public static string GridNumeroContrato {
            get {
                return ResourceManager.GetString("GridNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string GridProveedor {
            get {
                return ResourceManager.GetString("GridProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Documento.
        /// </summary>
        public static string GridTipoDocumento {
            get {
                return ResourceManager.GetString("GridTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Servicio.
        /// </summary>
        public static string GridTipoRequerimiento {
            get {
                return ResourceManager.GetString("GridTipoRequerimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Contrato.
        /// </summary>
        public static string GridTipoServicio {
            get {
                return ResourceManager.GetString("GridTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario de Creación.
        /// </summary>
        public static string GridUsuarioCreacion {
            get {
                return ResourceManager.GetString("GridUsuarioCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño del archivo supera lo máximo permitido (10 MB)..
        /// </summary>
        public static string MensajeValidacionTamanioArchivo {
            get {
                return ResourceManager.GetString("MensajeValidacionTamanioArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño de la imagen supera lo permitido (20kb)..
        /// </summary>
        public static string MensajeValidacionTamanioImagen {
            get {
                return ResourceManager.GetString("MensajeValidacionTamanioImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de confirmar la respuesta?.
        /// </summary>
        public static string MsjConfirmaRptaAutoriza {
            get {
                return ResourceManager.GetString("MsjConfirmaRptaAutoriza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar la respuesta de la autorización..
        /// </summary>
        public static string MsjValidaRptaAutorizador {
            get {
                return ResourceManager.GetString("MsjValidaRptaAutorizador", resourceCulture);
            }
        }
    }
}
